### ISSUE TITLE
猫抓 for chrome 1.0.15版本无法下载知乎视频。

### ISSUE THREAD

**Issue by justforadblock** [xifangczy/cat-catch#1]
测试网址：https://www.zhihu.com/question/269939406/answer/391508907
![1](https://user-images.githubusercontent.com/33308682/44126929-728b1ff4-a06d-11e8-9e7a-4a74f13eb564.jpg)

**Comment by justforadblock** [comment]
@xifangczy 麻烦看看，谢谢。

**Comment by xifangczy** [comment]
@justforadblock 视频是HLS 被切片了，点开放大镜有个m3u8解析工具，能一次性列出所有视频片段 然后用下载软件下载 再拼接成完整的视频。😐插件没办法自己拼接。
