### ISSUE TITLE
好像不支持斗鱼直播的下载？

### ISSUE THREAD

**Issue by lweo** [xifangczy/cat-catch#100]
**bug描述**
点下载，只是一个分片。。
**扩展**
 - 版本号
猫抓 v2.2.9

**浏览器**
 - chrome

**涉及网址**
https://www.douyu.com/5267001

**Comment by lweo** [comment]
> 因为是直播....😅

那个stream recorder插件却可以啊，希望能适配~

**Comment by xifangczy** [comment]
😅因为他的名字是 stream recorder (流媒体录制)
其实猫抓也有录制功能
其他功能 - hook脚本/录制脚本/屏幕捕捉
三个脚本都可以录制，但目前摆烂中.... 都有很多问题。具体查看用户文档
录制目前还不是猫抓的重点... 以后有时间会完善

**Comment by lweo** [comment]
> 因为他的名字是 stream recorder (流媒体录制) 我也很喜欢这个扩展😁
> 
> 其实猫抓也有录制功能 其他功能 - hook脚本/录制脚本/屏幕捕捉 三个脚本都可以录制，但目前摆烂中.... 都有很多问题。具体查看用户文档 录制目前还不是猫抓的重点... 以后有时间会完善
> 
> hook脚本的核心原理和stream recorder一样，只是最后输出的时候stream recorder做的更完美，我也正在向它学习。

谢谢大佬！你这个插件也很好用。stream recorder也有问题，长时间录制，也会出现下载失败的问题。他们好像是先下载分片，最后点保存时才去合并，如果分片数量过多，也容易崩。。

**Comment by lweo** [comment]
> 因为他的名字是 stream recorder (流媒体录制) 我也很喜欢这个扩展😁
> 
> 其实猫抓也有录制功能 其他功能 - hook脚本/录制脚本/屏幕捕捉 三个脚本都可以录制，但目前摆烂中.... 都有很多问题。具体查看用户文档 录制目前还不是猫抓的重点... 以后有时间会完善
> 
> hook脚本的核心原理和stream recorder一样，只是最后输出的时候stream recorder做的更完美，我也正在向它学习。

另外，屏幕捕捉是录制网页吗？是不是可以用来录制网页版的会议？比如zoom？

**Comment by xifangczy** [comment]
> 另外，屏幕捕捉是录制网页吗？是不是可以用来录制网页版的会议？比如zoom？

屏幕捕捉 就是利用会议相关的API实现的，可能会造成冲突。

长时间录制，不建议用任何扩展，扩展权限毕竟有限，js语言的效率对电脑要求也很高，页面崩溃了，不会保留任何数据。

**Comment by lweo** [comment]
> > 另外，屏幕捕捉是录制网页吗？是不是可以用来录制网页版的会议？比如zoom？
> 
> 屏幕捕捉 就是利用会议相关的API实现的，可能会造成冲突。
> 
> 长时间录制，不建议用任何扩展，扩展权限毕竟有限，js语言的效率对电脑要求也很高，页面崩溃了，不会保留任何数据。

原来如此。我试用了好几个扩展，长时间录制好像没有成功的… 
电脑性能倒还可以，i7 4代，12G ram

**Comment by lweo** [comment]
我想同时录制好几个会议，你有什么推荐的吗？除了录屏软件
