### ISSUE TITLE
对B站视频无效，不能预览

### ISSUE THREAD

**Issue by IiMM0811** [xifangczy/cat-catch#105]
**对B站视频无效，不能预览,芒果TV可以**

**扩展**
 - 2.29

**浏览器**
 -edge

**[涉及网址](https://www.bilibili.com/video/BV1fG4y137xy/?spm_id_from=333.1007.tianma.1-1-1.click&vd_source=1ef2cbf6f6d1d29f627b2663e6ea51ab)**

**Comment by xifangczy** [comment]
浏览器不支持直接预览m4s格式
