### ISSUE TITLE
央视视频下载画面有问题

### ISSUE THREAD

**Issue by StrollStars** [xifangczy/cat-catch#107]
**bug描述**
央视视频下载后，播放画面有问题，类似花屏。

**扩展**
2.2.9

**浏览器**
Chrome

**涉及网址**
https://tv.cctv.com/2022/08/08/VIDEETpCCHbN3yPWQoWiEADu220808.shtml

**Comment by xifangczy** [comment]
央视有一套自己的加密方法，没有通用解决方案，不会处理这个问题。

还有其他解决方案 `捕获脚本` `手机模拟` `深度搜索` 测试都可以拿到没加密的视频。

**Comment by StrollStars** [comment]
@xifangczy 感谢指教，已成功。
