### ISSUE TITLE
$title$获取网页标题不全

### ISSUE THREAD

**Issue by Watson-Bao** [xifangczy/cat-catch#108]
**bug描述**
网页标题中有`-` 符号时，` $title$` 获取的标题会在`-`前截断。
比如网页标题为` “简单易懂 Java/ C++/Python/js/go - 全排列(含有重复元素) - 全排列 II - 力扣（LeetCode）” `，
 `$title$`只能获取到` “简单易懂 Java&#47; C++&#47;Python&#47;js&#47;go”`，后面的获取不了
**扩展**
 - 版本号    猫抓 v2.2.9

**浏览器**
 - chromium 内核
 - firefox

**涉及网址**
https://leetcode.cn/problems/permutations-ii/solution/jian-dan-yi-dong-java-cpythonjsgo-quan-p-mt9u/

**Comment by xifangczy** [comment]
设置 修剪标题 `([^-|–]*)` 删掉 或者 改成 `(.*)`

**Comment by Watson-Bao** [comment]
感谢帮助，已解决
