### ISSUE TITLE
調用 N_m3u8DL-CLI 下載會缺少最後一個 ts 片段

### ISSUE THREAD

**Issue by i1itione** [xifangczy/cat-catch#111]
**bug描述**

不確定這是否為網站本身 ts 文件名命名規則的問題，或者是 N_m3u8DL-CLI 的選取範圍問題，
比方說共有 448 個文件需下載，然而 N_m3u8DL-CLI 的窗口卻顯示總下載數為 447 個，
因此我就在貓抓頁面打開顯示 m3u8DL 命令來確認，發現它的起始值為 0 而不是 1，
也就是它將下載 --downloadRange "0-447" 而不是 --downloadRange "1-448"，
但因為實際上第一個片段是從 1 開始，所以就變成它只下載了 1-447，因而缺少了第 448 個。 

**扩展**
2.3.0

**浏览器**
Google Chrome v108

**涉及网址**
https://hamivideo.hinet.net/index.do
註：選擇下載的是片源本身沒有 DRM 保護的

**Comment by xifangczy** [comment]
之前是从1开始，有人提交bug，总是会丢失第一个切片，经过测试 `--downloadRange` 参数 的确是从 0 开始的。
448个文件 正确范围应该是 0-447
我也测试了几个不同网站，一切正常。

**Comment by i1itione** [comment]
可能需要台灣 IP 才能打開頁面。

請問是否有可能在貓抓設置裡，添加自定義初始值為 0 或 1 的功能呢？

<img width="483" alt="P_20221229001" src="https://user-images.githubusercontent.com/21694907/209875447-81641bed-7996-478c-8c59-675b641eeb1f.png">

**Comment by xifangczy** [comment]
设置好了 m3u8DL 你可以直接点击资源列表页面 m3u8文件的下载按钮 不必进入解析器，这样不会自己添加downloadRange参数
![a](https://user-images.githubusercontent.com/1239904/209971669-dbbe338d-88d7-4a72-890b-bf7d0fe3ddd5.png)

**Comment by i1itione** [comment]
> 设置好了 m3u8DL 你可以直接点击资源列表页面 m3u8文件的下载按钮 不必进入解析器，这样不会自己添加downloadRange参数 ![a](https://user-images.githubusercontent.com/1239904/209971669-dbbe338d-88d7-4a72-890b-bf7d0fe3ddd5.png)

感謝解答，這樣確實就可正常下載了。
