### ISSUE TITLE
小小提议, 希望有多一点 "猫抓替换关键词" 的选择

### ISSUE THREAD

**Issue by DontNuts** [xifangczy/cat-catch#112]
小小提议, 希望有多一点 "猫抓替换关键词" 的选择

用于 N_m3u8DL-CLI 的替换关键词, 希望可以多一点, 尤其是用于档名的.
现在用于 --saveName 的只有 `$title$` 一个, 当遇上某些网站可能有多个 m3u8 的, 或者多个网站都有相同标题的, 就有些麻烦... (尤其是两个相同标题的视频同时下载时, 暂存资料夹内容会互相覆写)
所以希望加多些选择, 例如 `$time$`, `$filename$` (即是用 m3u8 的档名来做视频档名) 之类的.
如果可以或者再加个长度限制, 例如 `$title:50$` 就限制最长50字.
那么用户可以自由组合名字, 例如 `--saveName "$title:50$_$filename$"`

**Comment by xifangczy** [comment]
emmmmm 其实我后悔了 不清楚当初为什么选择 `$$` 符号...
使用 `{title}{date}` 比 `$title$$date$` 要清晰很多。
考虑 `$$` 仍然保持，新标签使用`{}`
