### ISSUE TITLE
解析不出来

### ISSUE THREAD

**Issue by louisZai** [xifangczy/cat-catch#115]
网址：http://tlbdsm888.com/（付费bdsm直播网站，有回放视频，需要购买。）
chrome版本：108.0.5359.125（正式版本） （64 位）
![1673103574301](https://user-images.githubusercontent.com/122164637/211157056-58f7f08a-f799-4f3a-b003-d39dd0c32f8f.png)
![1673103644292](https://user-images.githubusercontent.com/122164637/211157106-762a1814-d29f-46a0-909e-b9bc242a33a8.png)
一直加载中

**Comment by louisZai** [comment]
![1673104469504](https://user-images.githubusercontent.com/122164637/211157681-a033130b-de16-4eba-914c-d0ebd98f7238.png)

**Comment by xifangczy** [comment]
如果可以，以邮件方式 提供有播放权限的账号。
邮箱在 https://o2bmm.gitbook.io/cat-catch/issues
