### ISSUE TITLE
该媒体已加密，请注意下载key文件

### ISSUE THREAD

**Issue by 1259364843** [xifangczy/cat-catch#12]
该媒体已加密，请注意下载key文件
这个情况然后怎么操作呢
![image](https://user-images.githubusercontent.com/24851375/119802234-f70ae380-bf10-11eb-9303-2d3eefeafc74.png)

**Comment by xifangczy** [comment]
出现这个提示，第一行就是KEY文件下载地址。在合并的时候你需要手动处理一下m3u8文件才可以。
