### ISSUE TITLE
自动下载能下载m3u8吗

### ISSUE THREAD

**Issue by zhangzhy2000** [xifangczy/cat-catch#120]
自动下载好像只能调用chrome下载器下载，能否增加自动调用m3u8dl的选项呢。

**Comment by xifangczy** [comment]
额。。你确定看了设置项？

**Comment by zhangzhy2000** [comment]
> 额。。你确定看了设置项？

现在下载m3u8需要在popup中点一下才能下载，我想的是打开自动下载开关后，侦测到m3u8就可以立即下载，不用再额外点击。

**Comment by xifangczy** [comment]
emmmmm 我拒绝这个提议。。调用第三方程序还是手动点击的好。

**Comment by zhangzhy2000** [comment]
> emmmmm 我拒绝这个提议。。调用第三方程序还是手动点击的好。

emmmm行吧
