### ISSUE TITLE
在kiwi broswer上启用猫爪时崩溃

### ISSUE THREAD

**Issue by BlockyDeer** [xifangczy/cat-catch#121]
可以正常安装，但是我一旦点启用，浏览器会立即崩溃
![Uploading Screenshot_20230127_103600.jpg…]()

**Comment by xifangczy** [comment]
你可以试试几个老版本看。然后试出哪个版本开始不崩溃，告诉我。😂

**Comment by BlockyDeer** [comment]
好像是我的kiwi browser的问题，我试图启用油猴也会崩掉，算了，不在手机上用了
