### ISSUE TITLE
希望能添加暂停资源嗅探的功能

### ISSUE THREAD

**Issue by 1565211796** [xifangczy/cat-catch#122]
** 详细描述想要添 加/修改/增强 的功能 **
一点建议：
有些网站并不需要抓取资源下载，比如樱花动漫，但插件依然在运行不知道如何关闭，插件会在播放窗口上显示一个已经获取多少片段的那些提示，无法移动，点了关闭的❎按钮也会留下一个方框在播放器上遮挡……如果有个能暂停抓取的功能或许会比较方便？
![Snipaste_2023-01-29_13-52-28](https://user-images.githubusercontent.com/62823477/215308299-883b54c9-8d95-4138-a687-f190935dc4f2.png)
![Snipaste_2023-01-29_13-52-20](https://user-images.githubusercontent.com/62823477/215308302-6274ff41-15e7-487f-a577-2c35b4f3746f.png)

一点使用过程中发现的问题：
深度搜索功能确实很方便能抓取一些其他插件无法下载的视频，但这个功能下载下来的片段音视频是分开的需要自行合成，这个倒是无所谓可以自己用格式工厂混流搞定，但是抓取下载的音频文件会带有卡拉卡拉的电流音不知道是为什么……

**Comment by xifangczy** [comment]
你这个碎片捕获 不是猫抓插件，你应该是安装了油猴脚本 https://github.com/Momo707577045/media-source-extract

音频失真问题，因为音频容器不正确，需要用ffmpeg更改为 aac 然后再把音频和视频合并。
`ffmpeg -i audio -c copy audio.aac`
`ffmpeg -i audio.aac -i video.mp4 -c copy output.mp4`

**Comment by 1565211796** [comment]
多谢~关掉这歌脚本确实就好了，感谢!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月30日(星期一) 上午6:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xifangczy/cat-catch] 希望能添加暂停资源嗅探的功能 (Issue #122)





 
你这个碎片捕获 不是猫抓插件，你应该是安装了油猴脚本 https://github.com/Momo707577045/media-source-extract
 
音频失真问题，因为音频容器不正确，需要用ffmpeg更改为 aac 然后再把音频和视频合并。
 ffmpeg -i audio -c copy audio.aac
 ffmpeg -i audio.aac -i video.mp4 -c copy output.mp4
