### ISSUE TITLE
请问哪里可以设置 保存下载地址？ 好像怎么找到~ 谢谢

### ISSUE THREAD

**Issue by GOLDROBERT** [xifangczy/cat-catch#13]

**Comment by shuiRong** [comment]
应该不支持这个功能

**Comment by xifangczy** [comment]
应该很多人不会喜欢每次下载要选择下载位置吧。你可以自己修改一份
在
https://github.com/xifangczy/cat-catch/blob/5b0b05268c4f69983a608a02f9700cbf86b99c3d/js/popup.js#L90
处新增
`saveAs: true`
