### ISSUE TITLE
其他功能里面的ffmpeg输出文件失败

### ISSUE THREAD

**Issue by Keeevink** [xifangczy/cat-catch#132]
**其他功能里面的ffmpeg输出文件失败**

run FS.readFile output.mp4
Program terminated with exit(1)
Error: ffmpeg.FS('readFile', 'output.mp4') error. Check if the path exists
    at Object.U [as FS] (https://unpkg.com/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js:1:11538)
    at startFFmpeg (https://ffmpeg.bmmmd.com/js/ffmpeg.js?v20230221:32:29)
出现错误, 请复制Console信息到github提交bug

**扩展**
 - 版本号 猫抓 v2.3.1

**浏览器**

Microsoft Edge
版本 110.0.1587.56 (正式版本) (64 位)

**涉及网址**
https://ffmpeg.bmmmd.com/

**Comment by xifangczy** [comment]
日志不完整 涉及网址发出来

**Comment by Keeevink** [comment]
应该是文件数量太多了内存不够😄，BUG的任务有439个ts文件，我用本地的FFmpeg合并好了，刚刚试了一下171个的可以正常合并输出
