### ISSUE TITLE
如何设置每嗅探到一个ts地址就把视频保存到本地？

### ISSUE THREAD

**Issue by Huaweidev** [xifangczy/cat-catch#14]
在线网页直播时长4-5个小时，无法通过M3U8来直接下载完整直播视频，只能通过猫爪嗅探到每一个地址后，手工点击“下载全部”来下载切片视频。
但是嗅探了300个视频后点击“下载全部”突然发现提示“无法下载，文件不存在”。应该是密钥过期或者网址有效期失效了，很无奈。
有没有办法让猫爪嗅探到每个切片都自动下载保存到本地，这样就不用人工守在旁边不断点击下载了。
期待开发者的回复。

**Comment by xifangczy** [comment]
有这需求的人不多啊，不实用
