### ISSUE TITLE
url变换处理

### ISSUE THREAD

**Issue by corbamico** [xifangczy/cat-catch#143]
** 详细描述想要添 加/修改/增强 的功能 **
【需求1】调整：
是否可以文件名title的变换，可以放到stringModify(data.title)之前，
以方便正对原始title的正则变换

【需求2】增强：
增加一个regexp配置项，对下载链接的url进行处理：
某些视频网站(vimeo,akamaized)也需要进行url最后一段?r=abcde.....的删除： 
data.url = data.url.replace(reYoutube, "")

**Comment by xifangczy** [comment]
第二个 很早之前版本有这配置  由于是正则表达式非常影响效率 用处不大 有时候还导致无法下载 所以去掉了。

想不出还有什么场景需要去掉参数这个操作

**Comment by xifangczy** [comment]
可以用正则匹配
添加一条
(https?://.*akamaized\.net.*\.mp4)

**Comment by corbamico** [comment]
great, it works.
