### ISSUE TITLE
希望添加调整深度搜索抓取深度和范围的功能

### ISSUE THREAD

**Issue by 1249546799** [xifangczy/cat-catch#168]
您好，我在汇总多条音频的目录列表网址上使用猫抓时，
关闭搜索，无法嗅探到任何资源；但打开深度搜索，能只能嗅探到列表上前24条音频，并得到前24条音频的多组重复资源。
可能是猫抓的默认设置为避免意外下载占用过多磁盘空间，限制了深度搜索的文件数量。
希望添加调整深度搜索抓取深度和范围的功能，以便在一个音频列表网页通过深度搜索功能嗅探到列表上的"全部音频"。

同时使用下列正则表达式无法在深度搜索时去重
/^(?:(?:(?!\/).)+\/)?(.+)\.(mp3|wav|ogg)(?=\?|$)\s*($|\r?\n)(?!.*\1\.\2)/gi
/(.+)\.(mp3|wav|ogg)(?=\?|$)/gi

**Comment by xifangczy** [comment]
网址 看一看 涉及到账号 可以发到邮件
https://o2bmm.gitbook.io/cat-catch/issues

**Comment by 1249546799** [comment]
已在B站私信，非常感谢您的工作❤
