### ISSUE TITLE
希望为 Firefox 增加快捷键支持

### ISSUE THREAD

**Issue by Sostay** [xifangczy/cat-catch#170]
![image](https://github.com/xifangczy/cat-catch/assets/6897274/1a989295-0cd5-433e-a72e-44d9f6cb2a9f)
如图~

**Comment by xifangczy** [comment]
可以 你有什么提议吗？哪些功能想要快捷键

**Comment by Sostay** [comment]
> 可以 你有什么提议吗？哪些功能想要快捷键

能激活工具栏按钮就行哈~ （我用css把ff的地址栏隐藏了 常用扩展都是快捷键激活😂
