### ISSUE TITLE
自动下载文件名不能正常显示中文，且自动创建文件，不是直接下载到默认文件夹

### ISSUE THREAD

**Issue by zhuangyin8** [xifangczy/cat-catch#171]
**bug描述**
自动下载文件名不能正常显示中文，且自动创建文件夹，不是直接下载到默认文件夹

**扩展**
 - 版本号:2.3.3

**浏览器**
 - chromium 内核

**涉及网址**

**Comment by xifangczy** [comment]
> 不能正常显示中文

可以详细点描述吗

**Comment by zhuangyin8** [comment]
> > 不能正常显示中文
> 
> 可以详细点描述吗
正常应该是 139《精子的秘密》
实际下载文件名变成 139_E3_80_8A_E7_B2_BE_E5_AD_90_E7_9A_84_E7_A7_98_E5_AF_86_E3_80_8B

**Comment by xifangczy** [comment]
猫抓只会替换无法作为文件名的 `\/'":*?<>|~` 字符，不会处理成这样。这应该是原始文件名，你是否打开了 `使用自定义文件名保存文件(默认为网页标题)`

**Comment by xifangczy** [comment]
批量下载 会自动创建文件夹 这个会在下个版本默认取消。

**Comment by zhuangyin8** [comment]
下载地址是：https://mp3.xbdt4.cc/%E6%80%A7%E7%88%B1%E5%89%8D%E7%BA%BF/010%E3%80%8A%E9%81%BF%E5%AD%95%E3%80%8B.mp3
无法转义为中文名文件 010《避孕》.mp3

**Comment by zhuangyin8** [comment]
https://mp3.xbdt4.cc/%E5%B0%8F%E9%87%8E%E7%8C%AB/049%20%E7%B4%AB%E8%96%87%E5%91%BD%E4%BB%A4.mp3
自动下载文件名为：049_20_E7_B4_AB_E8_96_87_E5_91_BD_E4_BB_A4.mp3，而不是自动转义为：049 紫薇命令.mp3
