### ISSUE TITLE
ts添加参数 功能无法使用

### ISSUE THREAD

**Issue by duqian42707** [xifangczy/cat-catch#172]
**bug描述**

ts添加参数 这个功能该怎么用呢，点击按钮后页面直接刷新了，没看到可以输入参数的地方

**扩展**
 - 版本号 2.3.3

**浏览器**
 - chromium 内核

**涉及网址**

**Comment by duqian42707** [comment]
看了下代码，ts地址如果没有参数 添加m3u8地址的参数。
我改了一下，ts地址已有参数时也支持添加m3u8地址的参数：#173 。

**Comment by xifangczy** [comment]
这个功能... 其实是我给忘了😅很不常用...
