### ISSUE TITLE
m4a音频文件下载建议

### ISSUE THREAD

**Issue by TheLittleBoy** [xifangczy/cat-catch#174]
m4a是音频文件，下载后的后缀名被修改为mp4，能否不主动修改后缀名呢？

**Comment by xifangczy** [comment]
你是说 https://ffmpeg.bmmmd.com/ 么

**Comment by TheLittleBoy** [comment]
Chrome插件哦

**Comment by xifangczy** [comment]
插件是不会修改后缀的... 有涉及网址吗 我看看什么情况

**Comment by TheLittleBoy** [comment]
随便找了一个   https://y.qq.com/n/ryqq/player

**Comment by TheLittleBoy** [comment]
https://dl.stream.qqmusic.qq.com/C400000HZnr21f1glw.m4a?guid=7318515832&vkey=E7928A5C42B01AED6E6F2C9EECF313C20D67E785CCC2E029A0FFF189DF5E29519DD5D47E0053CC09B339FCE70D7A870F1E1F3ABBD2C109DC&uin=&fromtag=120032

**Comment by xifangczy** [comment]
测试了 我不管怎么下 都是原格式 m4a

**Comment by TheLittleBoy** [comment]
<img width="677" alt="image" src="https://github.com/xifangczy/cat-catch/assets/3365421/9a4c3539-1db2-4de8-bd3f-293afbf3a1a5">

有图为证啊

**Comment by TheLittleBoy** [comment]
右键另存为是mp4，用迅雷下载的是m4a
<img width="482" alt="image" src="https://github.com/xifangczy/cat-catch/assets/3365421/0ba801bb-ef5f-484c-96f5-f3168051344b">

**Comment by TheLittleBoy** [comment]
换Safari浏览器右键下载是m4a

**Comment by xifangczy** [comment]
chrome有问题 保存重要的数据 尝试重置chrome设置...

这个问题 我之前遇到过chrome总把jpg保存为jfif格式
windows系统可以通过注册表解决... mac os不知道解决办法...

**Comment by TheLittleBoy** [comment]
好吧。。
