### ISSUE TITLE
缓存捕捉视频标题自定义

### ISSUE THREAD

**Issue by Silfra-glacier** [xifangczy/cat-catch#176]
你好，希望增加缓存捕捉后下载视频时，可以自定义视频名称的功能，而不是默认选择网站的title作为视频的标题。
可以增加使用css、selector选择器或xpath等浏览器可以选中标签的功能，缓存捕捉完成时，下载时以该css选择器选中网页上的文字作为视频标题下载。
如果无法捕捉给定标题，则使用默认网站的title作为标题。或再给出提醒。谢谢！
![image](https://github.com/xifangczy/cat-catch/assets/68190236/49480125-95f9-49f3-9132-303b0fa447d1)
![image](https://github.com/xifangczy/cat-catch/assets/68190236/48954cc0-5a42-422c-9c4f-4d2cb5800489)

**Comment by Silfra-glacier** [comment]
有的视频标题不是网页的title

**Comment by xifangczy** [comment]
看情况把 需求的人多的话...

**Comment by chloe5685** [comment]
我也想说这个，我是用来爬音频的，好几个音频都是一样的名字，用起来的时候真的不方便

**Comment by Silfra-glacier** [comment]
现在可以自定义扩展捕获的视频或使用m3u8d下载的m3u8视频的名称了吗？我在设置里找到了有关选项，但没有找到具体如何设置，只有缓存捕捉时出现该选项。
![image](https://github.com/xifangczy/cat-catch/assets/68190236/7eff6c7a-94fb-4fa5-9de9-074d53a3d08b)
可以在设置界面设置匹配的网站默认使用某种规则，如对该网站捕获的m3u8文件，调用m3u8d下载时可以自动更改匹配到的视频名称。
