### ISSUE TITLE
網頁自動跳轉

### ISSUE THREAD

**Issue by 101408054** [xifangczy/cat-catch#182]
**bug描述**
邊下邊存.錄製直播。直播結束後該網頁會自動跳轉導致下載被取消。改怎麼處理呢?
謝謝
**扩展**
 - 版本号
猫抓 v2.4.1
**浏览器**
 - chromium 内核

**Comment by xifangczy** [comment]
可以暂时使用 `边下边存`  (注意不要勾选`mp4转码` 目前边下边存+mp4转码会有问题)
这些问题下个版本都会修复

**Comment by 101408054** [comment]
好的 謝謝你
