### ISSUE TITLE
 “媒体控制/其他功能”-“选择媒体” 检测不到媒体源

### ISSUE THREAD

**Issue by XIN-1** [xifangczy/cat-catch#185]
2.4.0 2.4.1 版本  “媒体控制/其他功能”-“选择媒体” 检测不到媒体源。
2.3.3版本正常识别到。

**Comment by xifangczy** [comment]
😂这是网站图标服务问题引起的。设置里暂时关掉 `显示网站图标`
我很少使用这个功能 发布前没发现这个bug
