### ISSUE TITLE
如何关闭自动下载转为手动点击下载?

### ISSUE THREAD

**Issue by murazi** [xifangczy/cat-catch#186]
**bug描述**
访问twitter,浏览一个视频,就会自动弹出下载

**扩展**
 - 版本号:2.4.1

**浏览器**
 - chromium 内核
版本 113.0.5672.127（正式版本） （64 位）

**涉及网址**
twitter.com

**Comment by xifangczy** [comment]
？？ 在哪打开的 再点一次就行了

**Comment by murazi** [comment]
算是解决了,将浏览器里的自动下载关闭,然后在TW每条文下方手动下载,但是好像还是有几率会触发,没太搞懂机制,没大碍,有相同问题的可以试一下~
