### ISSUE TITLE
钉钉群直播网页版无法解析m3u8地址，下载失败

### ISSUE THREAD

**Issue by BitOpiaGO** [xifangczy/cat-catch#189]
大佬您好。我用chrome的版本猫爪，想下载顶顶群直播，但是无法解析到有效的m3u8地址，想问问有办法么？
我使用缓存捕捉的方式能够成功下载全视频，感谢

![image](https://github.com/xifangczy/cat-catch/assets/136158825/4b47939c-07b5-4768-a82a-2597db3115ab)

**Comment by xifangczy** [comment]
这就有点麻烦了啊... 谁拉我进个群看看直播？？😂

**Comment by BitOpiaGO** [comment]
https://h5.dingtalk.com/group-live-share/index.htm?encCid=b0c6dc15dd870cfdccfeb40ceca958af&liveUuid=ccc396dd-b15b-4e2e-9912-33daad23e3ad#/ 
您要不试试这个地址，这个是公开可见的

**Comment by xifangczy** [comment]
又是一个一次性m3u8链接。播放器读取后 m3u8链接会立刻失效。猫抓就无法读取。。
可以使用 更多功能 中的 模拟手机 这个方法获得的m3u8就不是一次性的... 这个方法不知道多久就会失效...

**Comment by BitOpiaGO** [comment]
模拟手机后可以成功合并下载了，谢谢！
