### ISSUE TITLE
缓存捕获使用ffmpeg，文件名设置selecter，输出文件名有时候为out.mp4

### ISSUE THREAD

**Issue by sky7987** [xifangczy/cat-catch#192]
**bug描述**
缓存捕获使用ffmpeg，缓存完自动下载，文件名设置selecter，输出文件名有时候为out.mp4，一旦为out.mp4后，后面的都为这个名字了
**扩展**
 - 版本号
2.4.2
**浏览器**
 - chromium 内核

**涉及网址**
https://www.apecome.com/     此站需特定账号登录

**Comment by sky7987** [comment]
无需任何操作, 请耐心等待合并...成功后，自动下载文件
等待... 正在下载FFmpeg
load ffmpeg-core
loading ffmpeg-core
ffmpeg-core loaded
run FS.writeFile memoryVideo <45998229 bytes binary file>
run FS.writeFile memoryAudio <17849797 bytes binary file>
run ffmpeg command: -i memoryAudio -c:a copy audio.aac
ffmpeg version 9e96b1c Copyright (c) 2000-2020 the FFmpeg developers
  built with emcc (Emscripten gcc/clang-like replacement) 2.0.8 (d059fd603d0b45b584f634dc2365bc9e9a6ec1dd)
  configuration: --target-os=none --arch=x86_32 --enable-cross-compile --disable-x86asm --disable-inline-asm --disable-stripping --disable-programs --disable-doc --disable-debug --disable-runtime-cpudetect --disable-autodetect --extra-cflags='-O3 --closure 1 -I/src/build/include -s USE_PTHREADS=1' --extra-cxxflags='-O3 --closure 1 -I/src/build/include -s USE_PTHREADS=1' --extra-ldflags='-O3 --closure 1 -I/src/build/include -s USE_PTHREADS=1 -L/src/build/lib' --pkg-config-flags=--static --nm=llvm-nm --ar=emar --ranlib=emranlib --cc=emcc --cxx=em++ --objcc=emcc --dep-cc=emcc --enable-gpl --enable-nonfree --enable-zlib --enable-libx264 --enable-libx265 --enable-libvpx --enable-libwavpack --enable-libmp3lame --enable-libfdk-aac --enable-libtheora --enable-libvorbis --enable-libfreetype --enable-libopus --enable-libwebp --enable-libass --enable-libfribidi
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1a658c0] Duplicated SDTP atom
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'memoryAudio':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1
    creation_time   : 1970-01-01T00:00:02.000000Z
  Duration: 00:17:52.60, start: 0.000000, bitrate: 133 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:02.000000Z
      handler_name    : SoundHandler
Output #0, adts, to 'audio.aac':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1
    encoder         : Lavf58.45.100
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:02.000000Z
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
size=   16969kB time=00:17:52.41 bitrate= 129.6kbits/s speed=1.04e+04x    
video:0kB audio:16653kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.895927%
FFMPEG_END
run FS.readFile audio.aac
run ffmpeg command: -i memoryVideo -i audio.aac -c copy output.mp4
ffmpeg version 9e96b1c Copyright (c) 2000-2020 the FFmpeg developers
  built with emcc (Emscripten gcc/clang-like replacement) 2.0.8 (d059fd603d0b45b584f634dc2365bc9e9a6ec1dd)
  configuration: --target-os=none --arch=x86_32 --enable-cross-compile --disable-x86asm --disable-inline-asm --disable-stripping --disable-programs --disable-doc --disable-debug --disable-runtime-cpudetect --disable-autodetect --extra-cflags='-O3 --closure 1 -I/src/build/include -s USE_PTHREADS=1' --extra-cxxflags='-O3 --closure 1 -I/src/build/include -s USE_PTHREADS=1' --extra-ldflags='-O3 --closure 1 -I/src/build/include -s USE_PTHREADS=1 -L/src/build/lib' --pkg-config-flags=--static --nm=llvm-nm --ar=emar --ranlib=emranlib --cc=emcc --cxx=em++ --objcc=emcc --dep-cc=emcc --enable-gpl --enable-nonfree --enable-zlib --enable-libx264 --enable-libx265 --enable-libvpx --enable-libwavpack --enable-libmp3lame --enable-libfdk-aac --enable-libtheora --enable-libvorbis --enable-libfreetype --enable-libopus --enable-libwebp --enable-libass --enable-libfribidi
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1a65d40] Duplicated SDTP atom
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'memoryVideo':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1
    creation_time   : 1970-01-01T00:00:02.000000Z
  Duration: 00:17:52.60, start: 0.046444, bitrate: 343 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080, 341 kb/s, SAR 1:1 DAR 16:9, 10 fps, 10 tbr, 90k tbn, 20 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:02.000000Z
      handler_name    : VideoHandler
      encoder         : dailymotion/hls.js
[aac @ 0x1f6f700] Estimating duration from bitrate, this may be inaccurate
Input #1, aac, from 'audio.aac':
  Duration: 00:18:50.16, bitrate: 122 kb/s
    Stream #1:0: Audio: aac (LC), 44100 Hz, stereo, fltp, 122 kb/s
Output #0, mp4, to 'output.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1
    encoder         : Lavf58.45.100
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 341 kb/s, 10 fps, 10 tbr, 90k tbn, 90k tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:02.000000Z
      handler_name    : VideoHandler
      encoder         : dailymotion/hls.js
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 122 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
frame=10724 fps=0.0 q=-1.0 Lsize=   61849kB time=00:17:52.41 bitrate= 472.5kbits/s speed=3.75e+03x    
video:44730kB audio:16969kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.242937%
FFMPEG_END
run FS.readFile output.mp4
处理完毕, 正在生成并下载文件...
Program terminated with exit(1)

**Comment by xifangczy** [comment]
已经修复 等待下个版本发布。。
顺便增强了深度搜索 下个版本使用深度搜索后会在m3u8解析器里看到密钥。不用使用缓存捕获。

你可以Clone最新代码 然后 源码加载扩展 体验...

**Comment by sky7987** [comment]
> 已修复 等待下个版本发布。。 顺方便增强了深度搜索 下个版本使用深度搜索后会在m3u8解析器里看到密匙。不用使使用存储捕获。
> 
> 你可以克隆最新代码然后源码加载扩展体验反馈...

已测试正常
