### ISSUE TITLE
所有网站都是自动倍速播放

### ISSUE THREAD

**Issue by JXA-a** [xifangczy/cat-catch#196]
**bug描述**
所有网站打开视频播放都是默认倍数播放..  需要手动才可以正常播放，这个需要怎么修改？
<img width="782" alt="image" src="https://github.com/xifangczy/cat-catch/assets/36909175/3d28e592-2beb-4239-a0c5-3bdc98b6f318">

**扩展**
 - 猫抓 v2.4.2

**浏览器**
 Chrome 
版本 114.0.5735.133（正式版本） (x86_64)

**涉及网址**
YOUTUBE.COM
BILIBILI.COM
V.QQ.COM  几乎所有视频网站都是

**Comment by xifangczy** [comment]
猫抓没有主动修改默认倍数的功能... 请查看你安装了别的什么扩展。

**Comment by JXA-a** [comment]
> 

原来是https://greasyfork.org/zh-CN/scripts/30545-html5%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%B7%A5%E5%85%B7  这个插件的问题 记录的默认的倍数，但是为啥提示消息是由猫爪提醒的？

**Comment by xifangczy** [comment]
这很正常 点开媒体控制后 猫抓会持续的读取页面内媒体状态 然后更新按钮和选项...
媒体什么状态 就显示什么状态...

**Comment by JXA-a** [comment]
> 这很正常 点开媒体控制后 猫抓会持续的读取页面内媒体状态 然后更新按钮和选项... 媒体什么状态 就显示什么状态...

原来如此 我还以为是猫爪的问题...感谢解答
