### ISSUE TITLE
请问是否有计划开发firefox版本

### ISSUE THREAD

**Issue by Mixlining** [xifangczy/cat-catch#20]
请问是否有计划开发firefox版本，并上架商店

**Comment by mudarac** [comment]
hope that we can use with firefox

**Comment by xifangczy** [comment]
可以，目前考虑在firefox 和 Edge上发布 如果能发布成功的话。

**Comment by xifangczy** [comment]
firefox 还不支持Manifest v3
https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/
等支持了 会去发布
