### ISSUE TITLE
MediaSource劫持被检测出来了，缓存捕捉功能是用不了

### ISSUE THREAD

**Issue by xxyz30** [xifangczy/cat-catch#204]
TCPlayer似乎可以检测出来`MediaSource`类被劫持，然后缓存捕捉就会使用不了。虽然用其他模式可以捕捉，但感觉很不爽就是

版本2.4.3
浏览器 chrome
https://www.guancha.cn/politics/2023_05_12_692091.shtml

![图片](https://github.com/xifangczy/cat-catch/assets/81208875/0c73db1a-f387-4af0-bf4c-32caeeb570f0)

**Comment by xxyz30** [comment]
![图片](https://github.com/xifangczy/cat-catch/assets/81208875/d041e677-8ff0-44e2-84a7-d358f841f573)
这段代码是它的检测代码，不知道它怎么检测出来劫持的

**Comment by xifangczy** [comment]
https://github.com/xifangczy/cat-catch/commit/e3bf8a34b778bff73930800afd254652e5848dd6 已修复

你可以 下载最新源码 体验报告。。

**Comment by xxyz30** [comment]
> [e3bf8a3](https://github.com/xifangczy/cat-catch/commit/e3bf8a34b778bff73930800afd254652e5848dd6) 已修复
> 
> 你可以 下载最新源码 体验报告。。

woc这么快
