### ISSUE TITLE
解析或播放m3u8文件中有错误, 详细错误信息查看控制台

### ISSUE THREAD

**Issue by moxiewf** [xifangczy/cat-catch#221]
**bug描述**
点击解析按钮时打开的页面报错：解析或播放m3u8文件中有错误, 详细错误信息查看控制台，具体报错信息如下👇，按照下面的提示【删除Referer重新尝试、添加Referer重新尝试】都无效
![image](https://github.com/xifangczy/cat-catch/assets/26594602/6431f162-82a5-4459-a6e7-d63916be4195)

可否请大佬帮忙看看是不是我缺失了什么配置

**扩展**
 - 2.4.4

**浏览器**
 - chromium 内核
 - firefox
 都报一样的问题

**Comment by xifangczy** [comment]
解析器无法打开m3u8地址 你手动打开这个地址是否可以打开。
也有可能
这是假地址。
这是一次性地址 网站播放器读取后就销毁。

具体情况需要给出播放页面的地址 我去看看。。

**Comment by xifangczy** [comment]
看地址 大概率是某鹅通的视频
可以尝试 https://greasyfork.org/zh-CN/scripts/461963 这个脚本

**Comment by alextan2049** [comment]
我也遇到了同样的问题。救命~我试过之前的视频是可以下载的。但是今天这个就出错了。

**Comment by xifangczy** [comment]
> 我也遇到了同样的问题。救命~我试过之前的视频是可以下载的。但是今天这个就出错了。

不奇怪 他们也在随时更新 防止下载。我需要播放页面网址研究。。

**Comment by moxiewf** [comment]
> 看地址 大概率是某鹅通的视频 可以尝试 https://greasyfork.org/zh-CN/scripts/461963 这个脚本

感谢大佬回复！尝试过这个脚本仍有问题，已经通过邮件给大佬发送页面地址

**Comment by alextan2049** [comment]
刚刚更新了0.6脚本，还是下载密钥失败

**Comment by xifangczy** [comment]
> 刚刚更新了0.6脚本，还是下载密钥失败

网址。。

**Comment by alextan2049** [comment]
小鹅通登陆页面：&nbsp;https://study.xiaoe-tech.com/#/acount
登陆密码
15024306061
WANG123



小鹅通课程视频页面：
第2课 选材：建立一个属于你的故事材料库&nbsp; https://acad.ananas.com.cn/p/t_pc/course_pc_detail/video/v_6404cadce4b0fc5d123c1d90?product_id=term_63dcb12d387cd_0Lrrh2&amp;type=6



Alex&nbsp;tan
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xifangczy/cat-catch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月30日(星期三) 晚上8:40
***@***.***&gt;;
抄送:&nbsp;"Alex ***@***.******@***.***&gt;;
主题:&nbsp;Re: [xifangczy/cat-catch] 解析或播放m3u8文件中有错误, 详细错误信息查看控制台 (Issue #221)





  
刚刚更新了0.6脚本，还是下载密钥失败
  
网址。。

**Comment by xifangczy** [comment]
> 第2课 选材：建立一个属于你的故事材料库&nbsp; https://acad.ananas.com.cn/p/t_pc/course_pc_detail/video/v_6404cadce4b0fc5d123c1d90?product_id=term_63dcb12d387cd_0Lrrh2&amp;type=6

测试正常
请按照脚本的说明严格操作
https://greasyfork.org/zh-CN/scripts/461963

**Comment by moxiewf** [comment]
> > 感谢大佬回复！确实是某鹅通的。尝试过这个脚本仍有问题，已经通过邮件给大佬发送页面地址
> 
> 脚本已更新
已安装更新后脚本，问题已解决👍

**Comment by Sun-Coding** [comment]
> 我也遇到了同样的问题。救命~我试过之前的视频是可以下载的。但是今天这个就出错了。

记得篡改猴插件给开发者功能https://www.tampermonkey.net/faq.php#Q209，还有就是猫抓探嗅到很多文件只选择一个下载有问题，我选择了全部再下载，就会发现能顺利下载（但是出来很多下载标签页，但也没办法一个一个关掉）
