### ISSUE TITLE
2.4.5版本的缓存捕捉有bug

### ISSUE THREAD

**Issue by zhouwei-jazz** [xifangczy/cat-catch#239]
**bug描述**
因为学习需要缓存捕捉延河课堂的网课，这个网址的特点是左右两个画面都会有，左边是课堂实录，右边是PPT视频流。m3u8下不了，以前一直用缓存模式，会下载4个文件，分别是左边和右边的mp4视频和mp3音频。前几天自动给更新到2.4.5版本，再用缓存依然可以下载这么4个文件，但只有一边是正常的，另一边只有几mb。

换成2.4.4版本的话，一切正常

网址是www.yanhekt.cn

**Comment by xifangczy** [comment]
[猫抓2.4.6.zip](https://github.com/xifangczy/cat-catch/files/12790975/2.4.6.zip)
可以的话 测试这个版本是否正常

**Comment by zhouwei-jazz** [comment]
> [猫抓2.4.6.zip](https://github.com/xifangczy/cat-catch/files/12790975/2.4.6.zip) 测试这个版本是否正常

这回正常了，谢谢猫大
