### ISSUE TITLE
ffmpeg模式下提示“没有任何新文件输出, 请确认命令是否正确”

### ISSUE THREAD

**Issue by woterwang** [xifangczy/cat-catch#242]
**bug描述**
ffmpeg模式下，.ts文件是不是有默认限制，当前文件900+M，控制台提示 “没有任何新文件输出, 请确认命令是否正确”
`FFmpeg加载完毕
ffmpeg version 5.1.3 Copyright (c) 2000-2022 the FFmpeg developers
  built with emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.40 (5c27e79dd0a9c4e27ef2326841698cdd4f6b5784)
  configuration: --target-os=none --arch=x86_32 --enable-cross-compile --disable-asm --disable-stripping --disable-programs --disable-doc --disable-debug --disable-runtime-cpudetect --disable-autodetect --nm=emnm --ar=emar --ranlib=emranlib --cc=emcc --cxx=em++ --objcc=emcc --dep-cc=emcc --extra-cflags='-I/opt/include -O3 -msimd128' --extra-cxxflags='-I/opt/include -O3 -msimd128' --disable-pthreads --disable-w32threads --disable-os2threads --enable-gpl --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libopus --enable-zlib --enable-libwebp --enable-libfreetype --enable-libfribidi --enable-libass --enable-libzimg
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
memory1697025106608.ts: Invalid data found when processing input
Aborted()
没有任何新文件输出, 请确认命令是否正确`

**扩展**
 - ffmpeg version 5.1.3  
 - 猫抓 2.4.6

**浏览器**
 - chromium 内核 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

**涉及网址**

**Comment by xifangczy** [comment]
限制是2G大小

`Invalid data found when processing input`
这个应该是文件有问题 ts下载到本地看看能不能播发

**Comment by woterwang** [comment]
> 限制是2G大小
> 
> `Invalid data found when processing input` 这个应该是文件有问题 ts下载到本地看看能不能播发

感谢回复，提issues之前已经试过了，ts下载下来后无法播放，我理解老师的意思是文件本身的问题对吧

**Comment by xifangczy** [comment]
是的 也许是解密错误 密钥不正确等原因 ts没能顺利解密。

**Comment by woterwang** [comment]
> 是的 也许是解密错误 密钥不正确等原因 ts没能顺利解密合并

感谢，已经解决，确实是 密钥不正确 ，再次感谢，
