### ISSUE TITLE
文件名可以使用正则来获取网页上某一个标签的内容吗

### ISSUE THREAD

**Issue by Mikyjohhny** [xifangczy/cat-catch#252]
文件名可以使用正则来获取网页上某一个标签的内容吗，因为有的时候标题跟视频内容不相关

**Comment by Mikyjohhny** [comment]
比如说我想获取<h2>movie name</h2>中的movie name，调用N_m3u8DL-CLI下载的时候怎么将这个$title$参数替换成我用正则匹配到的这个名字

**Comment by xifangczy** [comment]
2.4.6已经有个新标签`${page}` 我还没写上文档。
把N_m3u8DL-CLI的saveName参数改为 `"${page|find:"h1"|exists:*,${title}_${now}}"`

更多标签用法 https://o2bmm.gitbook.io/cat-catch/docs/settings#keywords

**Comment by Mikyjohhny** [comment]
好的，谢谢作者大大~成功实现了

**Comment by QiTianzu** [comment]
> 2.4.6已经有个新标签`${page}` 和配套的find方法 我还没写上文档。 `${page}` 当前页面的dom `find` 就是 querySelector 把N_m3u8DL-CLI的saveName参数改为 `"${page|find:"h2"|exists:*,${title}_${now}}"` 页面查找 h2标签 如果没有使用 `${title}_${now}`
> 
> 更多标签用法 https://o2bmm.gitbook.io/cat-catch/docs/settings#keywords

请问要获取 `<div class="player-title">Player Title</div>` 中的 Player Title，--saveName 参数该怎么写呢？

**Comment by xifangczy** [comment]
> 获取 `<div class="player-title">Player Title</div>` 中的 Player Title，--saveName 参数该怎么写呢？

`--saveName "${page|find:".player-title"|exists:*,${title}_${now}}"`

**Comment by xifangczy** [comment]
> 为什么我的 Edge 和 Chrome 浏览器根本不认 ${page} 这个变量，设置里面设为 `--saveName "${page}"`，解析器页面显示命令里面还是显示为 `--saveName "${page}"`？

需要至少2.4.6版本猫抓。。。${page} 不能直接使用

**Comment by QiTianzu** [comment]
> > 为什么我的 Edge 和 Chrome 浏览器根本不认 ${page} 这个变量，设置里面设为 `--saveName "${page}"`，解析器页面显示命令里面还是显示为 `--saveName "${page}"`？
> 
> 需要至少2.4.6版本猫抓。。。${page} 不能直接使用

就是用的 2.4.6，浏览器也是最新版的。

**Comment by QiTianzu** [comment]
> > 为什么我的 Edge 和 Chrome 浏览器根本不认 ${page} 这个变量，设置里面设为 `--saveName "${page}"`，解析器页面显示命令里面还是显示为 `--saveName "${page}"`？
> 
> 需要至少2.4.6版本猫抓。。。${page} 不能直接使用

在播放视频的网页点 popup 页面中 m3u8 文件右侧的下载图标，调出的 N_m3u8DL-CLI 下载窗口里 File Name 为使用标签 ${page} 和配套的 find 方法匹配到的内容，而在猫抓 M3U8 解析器页面点“调用m3u8DL下载”调出的下载窗口里 File Name 则不是使用标签 ${page} 和配套的 find 方法匹配到的内容。

**Comment by dzdzdzd123** [comment]
> "${page|find:"h2"|exists:*,${title}_${now}}"

2.5.4版本测试page和find好像也没有

**Comment by dzdzdzd123** [comment]
> > "${page|find:"h2"|exists:*,${title}_${now}}"
> 
> 2.5.4版本测试page和find好像也没有

看到了，修改成pageDOM了
![023E3272](https://github.com/user-attachments/assets/aa46d79b-b2cb-4054-aa10-9175294d352e)

![023E2860](https://github.com/user-attachments/assets/5a43548c-81df-410d-94bf-ee47693b9647)
