### ISSUE TITLE
嗅探到资源点击下载，显示 “正在保存到硬盘”，然后就不动了

### ISSUE THREAD

**Issue by PjqDD** [xifangczy/cat-catch#253]
### 扩展版本号 extension version

2.4.6

### 浏览器

Google Chrome

### 浏览器版本号

117.0.5938.150

### 涉及网址

https://m.nianyin.com/wuxiaxuanhuan/1459/0-2.html

### 请详细描述问题

一直卡在这个页面不动
![image](https://github.com/xifangczy/cat-catch/assets/44695129/ae1e92bc-aa91-4c5e-8b94-9775e3439114)

浏览器标签进度显示100%
![image](https://github.com/xifangczy/cat-catch/assets/44695129/6c0fa959-fe6c-4fb1-b44c-624ed6516a22)

**Comment by PjqDD** [comment]
而且点右侧的下载按钮没反应，必须点二维码旁边的这个下载，才能跳转过去上边截图的下载页面
![image](https://github.com/xifangczy/cat-catch/assets/44695129/9927a103-a45a-4023-90af-1544b8211919)

**Comment by PjqDD** [comment]
@xifangczy 大佬，为啥关了呢？

**Comment by xifangczy** [comment]
> @xifangczy 大佬，为啥关了呢？

https://github.com/xifangczy/cat-catch/commit/01f76866ac67d05ba1f12302a61443a2cec99962
已经修了
