### ISSUE TITLE
Are there any plans to migrate this extension to Manifest V3?

### ISSUE THREAD

**Issue by jkyndir** [xifangczy/cat-catch#26]
First of all, all the glory to the dev of this extension. 
It really has helped a lot with my daily workflow.

Just wondering if there are any plans to migrate this extension to Manifest V3 from V2, since Manifest version 2 is deprecated by Google, and support for V2 will be removed in 2023. 

(BTW, Google as a company, really sucks ass, I know `.)

Really hope this project won't be orphaned.

**Comment by xifangczy** [comment]
It has been updated to V3.
