### ISSUE TITLE
下載Vimeo視頻沒聲音(m3u8預覽撥放有，但進下載頁面沒有)

### ISSUE THREAD

**Issue by zmh00** [xifangczy/cat-catch#265]
### 扩展版本号 extension version

v2.4.6

### 浏览器

Google Chrome

### 浏览器版本号

119.0.6045.160

### 涉及网址

學術會議平台(內部使用vimeo撥放器)

### 请详细描述问题

在預覽階段的播放有聲音:
![image](https://github.com/xifangczy/cat-catch/assets/17081794/ea02fa4c-b6cd-42e6-bc34-4ec9136bfeda)

但進入m3u8解析後就顯示無音頻下載後也確實無音頻
![image](https://github.com/xifangczy/cat-catch/assets/17081794/eb6de07f-e642-4b9a-95c5-ab323ed9ddcc)

嘗試過:
1.網頁內部的資源探索都嘗試下載過沒有一個是聲音的資源
2.參考之前的issue有關閉"刷新、跳转到新页面 清空当前标签抓取的数据"

Please note: I am truly grateful to the creator of this extension, as it has helped me save many videos in the past.

**Comment by xifangczy** [comment]
预览的url 和m3u8解析器的m3u8文件地址 不一致。
把预览的url发来看看 或者把预览的m3u8下载到本地 看看内容。

**Comment by zmh00** [comment]
後來檢查一開始的一級m3u8文件，內部是有音訊、字幕、多個不同解析度的影片次級m3u8連結
解析後，只提供特定的解析度選擇，進入後只有該解析度影片的次級m3u8片段內容
謝謝作者!!
