### ISSUE TITLE
Aria2 RPC 密钥如何填写

### ISSUE THREAD

**Issue by asong2022** [xifangczy/cat-catch#271]
** 详细描述想要添 加/修改/增强 的功能 **
我看到有Aria2 RPC 功能非常惊喜，请问下Aria2 RPC 密钥填写在哪里呀

**Comment by xifangczy** [comment]
2.4.7 暂不支持 

目前已经支持了密钥 Clone最新代码试用

**Comment by asong2022** [comment]
> 2.4.7 暂不支持
> 
> 目前已经支持了密钥 Clone最新代码试用

谢谢！我等正式更新吧，我用aria2拓展插件也能配合着先用用，就是还做不到m3u8也能直接通过猫抓推送到nas的n_m3u8dl下载到nas，mp4可以用aria2RPC推送了。
