### ISSUE TITLE
猫抓 M3U8 解析器页面调用 m3u8DL 下载命令参数无法获取 Referer

### ISSUE THREAD

**Issue by QiTianzu** [xifangczy/cat-catch#272]
### 扩展版本号 extension version

v2.4.7

### 浏览器

Chromium

### 请详细描述问题

N_m3u8DL-CLI 参数设置中包含 ${referer|exists:'--headers "Referer:*"'}，在播放视频的网页点 popup 页面中 m3u8 文件右侧的下载图标，调出的 N_m3u8DL-CLI 下载任务的命令参数就具有包含 Referer 的 --headers 选项。

**Comment by QiTianzu** [comment]
应该是这个提交 d177d5e3a80fe197ce701ab4a6f4a2b05124f960 导致的，并且这个修复 9f1f442c6b5b165eac7f6fd2c27bc3ecc3b49a91 也失效了。

**Comment by xifangczy** [comment]
${referer|exists:'--headers "Referer:*"'} 是按照预期的工作。如果存在referer 就写入 --headers 选项

无法获取网页内容的问题已经修复

**Comment by QiTianzu** [comment]
> ${referer|exists:'--headers "Referer:*"'} 预期的工作就是 如果存在referer 就写入 --headers 选项
> 
> 无法获取网页内容的问题已经修复

同样的网页，在这个提交 d177d5e3a80fe197ce701ab4a6f4a2b05124f960 之前就能写入 --headers 选项，之后就不行了。

**Comment by xifangczy** [comment]
> 同样的网页，在这个提交 [d177d5e](https://github.com/xifangczy/cat-catch/commit/d177d5e3a80fe197ce701ab4a6f4a2b05124f960) 之前就能写入 --headers 选项，之后就不行了。

方便的话 网址给我 具体看看

**Comment by QiTianzu** [comment]
> > 同样的网页，在这个提交 [d177d5e](https://github.com/xifangczy/cat-catch/commit/d177d5e3a80fe197ce701ab4a6f4a2b05124f960) 之前就能写入 --headers 选项，之后就不行了。
> 
> 方便的话 网址给我 具体看看

https://www.iole.tv/vodplay/37820-1-1.html
