### ISSUE TITLE
M3U8DL使用新下载器，超过2G文件，不会跳保存框

### ISSUE THREAD

**Issue by wildwolfzj** [xifangczy/cat-catch#277]
### 扩展版本号 extension version

2.4.7

### 浏览器

Google Chrome

### 涉及网址

https://weibo.com/l/wblive/p/show/1022:2321324925923832234690

### 请详细描述问题

M3U8DL使用“新下载器”，超过2G文件，只会提示，不会跳保存框
勾除新下载器，就正常了。
但默认是勾着的

**Comment by xifangczy** [comment]
勾选了 在线ffmpeg转码 遇到2G以上的文件 新下载器就退出了。

现在已修正
