### ISSUE TITLE
下载大于2G的视频之后不转到在线FFmepg，然后怎么储存已经下载完成的资源呢

### ISSUE THREAD

**Issue by KriszzzzZ** [xifangczy/cat-catch#278]
### 浏览器

Google Chrome

### 请详细描述问题

在勾选了FFmpeg转码的情况下，同时视频不小心超过了2G，此时无法跳转到在线FFmpeg界面。在这种情况下，如何把已经下载好的视频资源合并并输出到本地磁盘呢？

**Comment by xifangczy** [comment]
取消 新下载器 选项。这个bug下个版本修复

**Comment by KriszzzzZ** [comment]
> 取消 新下载器 选项。这个bug下个版本修复
谢谢！！！这么晚了还能回复！！
