### ISSUE TITLE
2.4.8无法复制地址了

### ISSUE THREAD

**Issue by lvzhenbo** [xifangczy/cat-catch#281]
### 扩展版本号 extension version

2.4.8

### 浏览器

Google Chrome

### 浏览器版本号

120.0.6099.130

### 涉及网址

都一样的

### 请详细描述问题

无法复制地址，复制按钮出来是这个东西
`$url$`

**Comment by lvzhenbo** [comment]
![image](https://github.com/xifangczy/cat-catch/assets/32427677/9a5a4ce5-7b27-4c8b-92a5-c39351801faa)
啊？

**Comment by xifangczy** [comment]
从 2.4.7开始就不支持 `$url$` 标签了。
在设置 复制选项 都改为 `${url}`

**Comment by lvzhenbo** [comment]
> 从 2.4.7开始就不支持 `$url$` 标签了。 在设置 复制选项 都改为 `${url}`

没懂，对于用户来说我设置都没有改过，原来一模一样的，你这破坏性更改也太那啥了吧，至少说能够在某个显眼的地方提示一下。我这找了半天代码不知道什么问题，结果和我说是原来设置得手动改

**Comment by xifangczy** [comment]
2.3.0加入的 `$url$` 2.3.1就取消了。
为了丢掉这个历史包袱。。确实对2.3.0安装的用户 牺牲有点大。。

**Comment by lvzhenbo** [comment]
> 2.3.0加入的 `$url$` 2.3.1就取消了。一直兼容到现在。。
> 为了丢掉这个历史包袱。。确实对2.3.0安装的用户 牺牲有点大。。

我不是说这个改动不好。因为对于用户来说，这个功能不能用就是bug，这也是我自己开发过程中的遇到过的问题。其实就非常简单。如果这是一个涉及高级功能，一般用户用不到的，那么在功能里提个醒。如果这是一个低级功能，一般用户也不会去改的，那就强制改掉，或者在非常醒目的地方提个醒。这样就不会造成问题，我知道对于开发者来说这不是bug，但是这是用户体验，对于用户来说不能用，你也啥都没说，那就是bug。

**Comment by xifangczy** [comment]
你说的对 的确欠考虑。我低估了后果和2.3.0的安装量。尽快推送下一个版本 解决这个问题。

**Comment by gggccc44** [comment]
感觉更新的时候加个提示修改参数。。。我又发了个提醒的议题，因为不是所有用户都会来找解决办法，尤其github访问还挺麻烦的，如果没梯子的话
