### ISSUE TITLE
猫抓在腾讯会议只能捕获flv，无法捕获m3u8

### ISSUE THREAD

**Issue by 775405984** [xifangczy/cat-catch#285]
** 详细描述想要添 加/修改/增强 的功能 **
https://meeting.tencent.com/live/13190760744079821876
播放后，猫抓可以准确识别flv是https://liveplay.wemeet.tencent.com/trtc_1400143280/stream_13190760744079821876_230863895.flv?txTime=658d206d&txSecret=5A8C7173AD820D01F582DA48EE1C69BF
然而，用devtools捕捉到的flv地址是在这个链接里面: https://meeting.tencent.com/wemeet-tapi/liveportal/v2/query_live_stream?c_os=web&c_os_version=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/102.0.0.0%20Safari/537.36&c_os_model=web&c_timestamp=1703748174654&c_instance_id=5&c_nonce=WY2GxAjCc&c_app_uid=144115233556116767&c_app_id=null&c_app_version=&c_token=null&c_platform=0
![image](https://github.com/xifangczy/cat-catch/assets/7196377/a32f2748-e207-4c5f-9ae3-141b73c1d854)
对于该链接，打开后可以看到m3u8地址:
![image](https://github.com/xifangczy/cat-catch/assets/7196377/599c3f3b-ba78-45bf-b4ad-070c42b05b3e)

请问各位: 为什么猫抓不能嗅探到这个m3u8链接？是因为这个网页默认的播放协议是flv吗？抖音网页版直播也是一样。

**Comment by xifangczy** [comment]
默认估计是flv
理论上使用深度搜索能找到 试试看？

**Comment by 775405984** [comment]
还有深度搜索，真的可以，谢谢
