### ISSUE TITLE
猫抓可以实现某扩展的【潜在秘钥】功能吗？

### ISSUE THREAD

**Issue by 775405984** [xifangczy/cat-catch#287]
** 详细描述想要添 加/修改/增强 的功能 **
[这个网站](https://www.sciconf.cn/m/lives/details/16437?video_id=249745&lang=cn)打开后播放可以在[某插件](http://www.filecxx.com/zh_CN/index.html)里找到秘钥
![image](https://github.com/xifangczy/cat-catch/assets/7196377/02667998-a624-4674-8a61-ffe87c01171b)

请问猫抓可以实现吗？
新年快乐啊大佬

**Comment by xifangczy** [comment]
使用深度搜索 https://o2bmm.gitbook.io/cat-catch/docs/popup-1#shen-du-sou-suo
