### ISSUE TITLE
新版改设置参数了，升级后该给个提示啊

### ISSUE THREAD

**Issue by gggccc44** [xifangczy/cat-catch#289]
### 扩展版本号 extension version

2.4.8

### 浏览器

Google Chrome

### 浏览器版本号

Chromium 102.0.5005.167

### 涉及网址

missav.com

### 请详细描述问题

以前是"$url$"我找了半天问题重置设置发现变成"${url}"了。另外看到其他人反馈的复制地址问题，看回复也是要改设置。我的意思是改动版本后给个提示，不是所有用户都会来github翻议题的，能看帮助已经是达人了。
以上只是建议，猫抓已经很好用了不苛求。看了反馈我还是发了这个议题（虽然不是绝对必要）只希望更好

**Comment by gggccc44** [comment]
另外以前反馈过生效域的问题，个人不清楚功能实现麻烦不，因为抓取好像是消耗内存的方式，个人建议可以白名单或者黑名单，我目前是用暂停方式，但是经常会忘，貌似开了后内存消耗会更快，幸好我48G内存还行

**Comment by gggccc44** [comment]
还有可以加个赞助二维码，白嫖这么久挺不好意思的，找了下没有，我一般也不多就10块，赞助过一些扩展或者脚本了，虽然不多起码多少会有觉得有认可的感觉吧

**Comment by gggccc44** [comment]
看到赞助码了，在那个下载转换界面里？第一次用这功能，我通常用m3u8dl下载没看到过，一会捐助10元支持

**Comment by xifangczy** [comment]
感谢支持

抓取不消耗内存 猫抓下载 合并下载 才会消耗内存。

shift+esc 查看任务管理器 如果你发现  jfedfbgedapdagkghmgibemcoggfppbb (edge是oohmdefbjalncfplafanlagojlakmjci) 占用了过多内存。请联系我，并把详细操作步骤告诉我。也许有些内存泄漏。
但目前都没遇到过
