### ISSUE TITLE
笨猫猫 NES 在线 ffmpeg 的 ffmpeg-core.wasm 加载失败

### ISSUE THREAD

**Issue by make17better** [xifangczy/cat-catch#291]
### 浏览器

Firefox

### 涉及网址

https://ffmpeg.bmmmd.com/

### 请详细描述问题

换过网络、电脑、浏览器，也挂过代理，都报 403，可能是 CDN 拒绝访问该文件了。
![图片](https://github.com/xifangczy/cat-catch/assets/45524718/a357461c-35ba-4274-ab8f-5c4a3cbdeec9)

**Comment by xifangczy** [comment]
理论上应该会自动选择一个可以获取的cdn... 你firefox什么版本？

没办法 ffmpeg-core.wasm 太大 很多加速cdn都把ffmpeg-core.wasm屏蔽了。

**Comment by make17better** [comment]
> 理论上应该会自动选择一个可以获取的cdn... 你firefox什么版本？
> 
> 没办法 ffmpeg-core.wasm 太大 很多加速cdn都把ffmpeg-core.wasm屏蔽了。

![图片](https://github.com/xifangczy/cat-catch/assets/45524718/92c6d856-3f0f-4f85-8cd1-03381290179c)

**Comment by make17better** [comment]
> 经过测试 firefox dev 122版确实有这个问题 迷之原因。。暂时 请使用正式版。。 如果未来firefox 122 正式版 再出现这样的问题 我再看看具体什么原因。
> 
> 顺便测试了chromium的122版本 都没这个问题。。

好的，辛苦啦。

**Comment by xifangczy** [comment]
问题已修复
