### ISSUE TITLE
小鹅通专栏里的系列课程，有个别课程开放了播放权限，但专栏却设了密码，有办法获取到密码或绕过这个限制吗？

### ISSUE THREAD

**Issue by lweo** [xifangczy/cat-catch#298]
** 详细描述想要添 加/修改/增强 的功能 **
小鹅通的专栏，是手动加入已存在的视频，有的视频的权限是开放的，视频下会显示该视频所在的专栏，但专栏访问却设了密码，有办法获取到整个专栏的视频吗？

**Comment by xifangczy** [comment]
不能...
