### ISSUE TITLE
抓取过后的二维码 链接 的保存时间  

### ISSUE THREAD

**Issue by 2797635026** [xifangczy/cat-catch#299]
** 详细描述想要添 加/修改/增强 的功能 **
 自己迅雷下的太慢 想把之前的二维码分享给好友 这个二维码或者链接有时间限制吗   还是过一段时间小时

**Comment by xifangczy** [comment]
如果网站对资源有来源验证，分享出去就无法打开。多久时效，是取决于网站对资源链接的管理，这不是猫抓能影响的事情。
