### ISSUE TITLE
腾讯视频网站抓取不到M3U8文件，有解决办法吗？

### ISSUE THREAD

**Issue by upleung** [xifangczy/cat-catch#3]
腾讯视频链接：https://v.qq.com/x/cover/m441e3rjq9kwpsc/u0031yygc9w.html

这是VIP视频，已经开通会员，我想下载到本地看；
一个月前还可以抓取到M3U8，现在抓不到了，什么原因？

**Comment by tianxuanzhizi** [comment]
可以用get video

**Comment by xxmmllqqqqccqq** [comment]
遇到同样的问题。。。

**Comment by xifangczy** [comment]
很可能更改了播放方式呗，很多大型视频网站都不会用传统的m3u8，都会自己写js控制切片和密钥。猫抓不会为了针对某个网站写特定的代码，那太累了，如果想抓，可以用youtube-dl
