### ISSUE TITLE
小破站 能嗅到，也能正常预览，但无法下载

### ISSUE THREAD

**Issue by NanoRocky** [xifangczy/cat-catch#301]
### 扩展版本号 extension version

v2.4.9

### 浏览器

Microsoft Edge

### 浏览器版本号

v121.0.2277.83

### 涉及网址

https://www.bilibili.com

### 请详细描述问题

小破站能正常嗅到视频和音频2个m4s，也都能正常预览，但点击下载会报错 “{"readystate":0,"status":0,"statustext":"error"}” ，然后 Edge 弹出下载框提示 “没有权限” 。试过 “携带请求头下载” 也是一样的效果...
![QQ截图20240126094703](https://github.com/xifangczy/cat-catch/assets/76585834/a6487508-1cef-4e4c-98c6-e1f988debce6)
![QQ截图20240126094736](https://github.com/xifangczy/cat-catch/assets/76585834/71cd69a9-3d0f-4ab9-9617-da0f07d38059)

**Comment by xifangczy** [comment]
刚刚测试了下 一切正常。。你尝试刷新下 获取新的资源地址再下载。。也许是资源地址已经被回收。

**Comment by NanoRocky** [comment]
并不是资源的问题。我也努力排查了一下，最后发现如果在拓展设置内将 “站点访问权限” 改为 “单击时”，即使启用插件后 Edge 会自动刷新该网页，但拓展在下载时就会出现 “{"readystate":0,"status":0,"statustext":"error"}” 问题...设置为 “在所有站点上” 就能正常工作，也并不是只崩小破站。之前我一直都是设置成 “单击时” 的，额也是为了减少占用叭...但最近更新后好像就会出问题了....也可能是 Edge 的锅...？

**Comment by xifangczy** [comment]
打开 "点击时" chrome.declarativeNetRequest API确实会失效。应该是属于bug 扩展页面不应该受到这种限制。

如果你仍然想保持 "点击时"
可以通过 Aria2 RPC 下载 推荐本地下载工具 https://github.com/agalwood/Motrix 支持aria2 rpc协议添加下载

另外猫抓也自带暂停功能，暂停后不再记录和判断任何资源，可以明显减少资源占用。
