### ISSUE TITLE
FFmpeg加载失败

### ISSUE THREAD

**Issue by hbdjks** [xifangczy/cat-catch#302]
### 扩展版本号 extension version

v2.4.9

### 浏览器

Firefox

### 浏览器版本号

122.0.0.0

### 涉及网址

https://ffmpeg.bmmmd.com/

### 请详细描述问题

FFmpeg加载失败
![2024-01-28](https://github.com/xifangczy/cat-catch/assets/62651446/cb9ae697-76d2-43e1-93a8-34aee2196de3)

**Comment by xifangczy** [comment]
该来的还是来了，firefox dev版就有人报过bug 正式版还是存在，我检查下。

**Comment by xifangczy** [comment]
加了个补丁, 修正了firefox的问题, 清空浏览器缓存刷新一下。

**Comment by hbdjks** [comment]
好了，“FFmpeg加载完成 ffmpeg core v0.12.6”，可以了，感謝！
