### ISSUE TITLE
ipad 的浏览器怎么导入


### ISSUE THREAD

**Issue by 2797635026** [xifangczy/cat-catch#307]
** 详细描述想要添 加/修改/增强 的功能 **
![IMG_20240207_233744.jpg](https://g![IMG_20240207_233736.jpg](https://github.com/xifangczy/cat-catch/assets/77963683/b47bbef6-cc3f-4c15-886a-9d791ebf240b)

/77963683/0723c956-b4f4-4770-80fa-98f07b53febb)

![正在上传 IMG_20240207_233736.jpg…]()

**Comment by 2797635026** [comment]
![IMG_20240207_233744.jpg](https://github.com/xifangczy/cat-catch/assets/77963683/27b0d67d-3bda-4dab-af5d-474012852d03)

这是ipad上stay插件 可以导入链接或者代码 代码在哪找

**Comment by lxxxp09** [comment]
哥们你解决了吗 我也想在stay上用

**Comment by 2797635026** [comment]
> 哥们你解决了吗 我也想在stay上用

你把脚本复制下来 导进去
