### ISSUE TITLE
重装edge后不能抓取了

### ISSUE THREAD

**Issue by pjq2926** [xifangczy/cat-catch#313]
### 扩展版本号 extension version

2.5.1

### 浏览器

Microsoft Edge

### 浏览器版本号

版本 122.0.2365.66 (正式版本) (64 位)

### 涉及网址

https://live.kankanews.com/huikan/

### 请详细描述问题

重装过一次edge，现在总显示“数据下载中”，不能抓取。其他设备如macos上同账户edge中的猫抓就正常。不知道该怎么弄？
![Uploading screenshot-1709643131330.png…]()

**Comment by xifangczy** [comment]
图片炸了。。重新传下
