### ISSUE TITLE
请问猫抓在浏览器插件栏显示的数字如何关掉？

### ISSUE THREAD

**Issue by DeeEi** [xifangczy/cat-catch#319]
![圖片](https://github.com/xifangczy/cat-catch/assets/114544709/81eeeba6-08a2-4af1-af9f-f51a723089eb)
这个数字请问怎么关掉？
我看了猫抓设置，没有找到这个关闭功能。

**Comment by xifangczy** [comment]
额。。无法关闭。。如果你不需要 可以点击`暂停`按钮

**Comment by DeeEi** [comment]
@xifangczy 能否增加这个关闭功能，其他插件普遍也有关闭数字显示这个选项。
