### ISSUE TITLE
twitter下载的短视频没有音频了

### ISSUE THREAD

**Issue by zszen** [xifangczy/cat-catch#321]
### 扩展版本号 extension version

v2.4.5

### 浏览器

Firefox

### 浏览器版本号

123.0

### 涉及网址

https://twitter.com

### 请详细描述问题

通过m3u8解析出来下载的视频不带音频，完全没声音了

**Comment by xifangczy** [comment]
twitter的m3u8 现在是音频和视频是分离的。
有两个方法

勾选一个音频m3u8和视频m3u8 会出现合并下载按钮

解析第一个 m3u8列表文件 会出现分辨率和音频选择 点击你需要的分辨率和音频 发送到在线ffmpeg 后在在线ffmpeg页面 选择 音频+视频合并 运行命令

**Comment by zszen** [comment]
> 勾选一个音频m3u8和一个视频m3u8 会出现合并下载按钮

貌似不会，只会下载信息文件

**Comment by xifangczy** [comment]
> 貌似不会，只会下载信息文件

确保猫抓版本在 2.5.1

**Comment by zszen** [comment]
> > 貌似不会，只会下载信息文件
> 
> 确保猫抓版本在 2.5.1

好的，单视频不能自动下了

**Comment by zszen** [comment]
> > 貌似不会，只会下载信息文件
> 
> 确保猫抓版本在 2.5.1

好的，单视频不能自动下了

**Comment by cyfex** [comment]
@xifangczy 能开发一个自动合并功能吗？这个操作限制有点多，比如在线ffmpeg只能转2GB以下的文件
