### ISSUE TITLE
最新版本还是有点问题？很多网页的m3u8文件没有抓取成功？

### ISSUE THREAD

**Issue by jkyndir** [xifangczy/cat-catch#33]
如题。

召唤大佬
跪求大佬

**Comment by xifangczy** [comment]
举个例子？

**Comment by hujincheng2009** [comment]
> 举个例子？

例子还不简单，随便一个樱花动漫他就抓不住，1.0.16版本就可以 而新版本就抓不住任何东西
![屏幕截图 2022-05-23 202738](https://user-images.githubusercontent.com/18724420/169883730-4da5cd9f-66a5-4514-b1de-2f2cb306572d.png)
![屏幕截图 2022-05-23 202722](https://user-images.githubusercontent.com/18724420/169883736-a7c8cfdd-fa5f-4c39-8723-21ebe26ea47b.png)

**Comment by xifangczy** [comment]
没问题。你尝试在设置页面里面 重置所有设置 了吗？
因为升级跨度大 需要重新设置。

**Comment by hujincheng2009** [comment]
> 没问题。你尝试在设置页面里面 重置所有设置 了吗？ 因为升级跨度大 需要重新设置。

不太清楚咋设置
还有就是有角标蓝色1但打开没有链接
![Frame 173](https://user-images.githubusercontent.com/18724420/170002948-66a96a03-6a96-4d28-bce4-c933580f7a1d.jpg)

**Comment by xifangczy** [comment]
在设置页面 点击 重置所有设置 按钮
