### ISSUE TITLE
可以嗅探下载PDF文件吗

### ISSUE THREAD

**Issue by wx69wx** [xifangczy/cat-catch#333]
** 详细描述想要添 加/修改/增强 的功能 **
可以嗅探下载PDF文件吗？谢谢！

**Comment by xifangczy** [comment]
添加 `pdf` 后缀 和  `application/pdf` 类型 也许能找到一部分。
大部分网站 都不是直接给出pdf文件 而是通过自有格式 呈现出类似 pdf效果 而不是真的pdf。

**Comment by wx69wx** [comment]
好的，谢谢大佬答复！
