### ISSUE TITLE
请问博主在线的ffmpeg能否开源

### ISSUE THREAD

**Issue by hubyao** [xifangczy/cat-catch#334]
请问博主在线的ffmpeg能否开源

**Comment by xifangczy** [comment]
在线ffmpeg就是html+js+css 等于开源的。最大问题是ffmpeg wasm文件 30MB+ 目前用的大家捐款来的cdn 如果你要自建，需要自己想办法。

**Comment by asong2022** [comment]
> 在线ffmpeg就是html+js+css 等于开源的，没有工程化。 最大问题是ffmpeg wasm文件 30MB+ 目前用的大家捐款来的cdn 如果你要自建，需要自己想办法。

请问下，博主这个在线的ffmpeg，合并ts的功能能做个小工具吗，我用N_m3u8有时候下载中断了就是一堆ts，ts个数太多，放在线ffmpeg合并大小超了，就不知道如何合并了

**Comment by xifangczy** [comment]
> 请问下，博主这个在线的ffmpeg，合并ts的功能能做个小工具吗，我用N_m3u8有时候下载中断了就是一堆ts，ts个数太多，放在线ffmpeg合并大小超了，就不知道如何合并了

那为什么不使用本地ffmpeg？？
https://github.com/BtbN/FFmpeg-Builds/releases
