### ISSUE TITLE
能增加mpv 播放，并传递referer参数么？

### ISSUE THREAD

**Issue by zzyyi66** [xifangczy/cat-catch#34]
能增加mpv 播放，并传递referer参数么？

**Comment by xifangczy** [comment]
能调用potplayer 是利用了他的伪协议功能 "potplayer://"
mpv 认为伪协议不安全，没有伪协议功能。所以暂时没办法调用mpv播放器。

**Comment by 986244073** [comment]
我试了下 可以调用mpv

**Comment by Noah1995** [comment]
> 我试了一下可以调用 mpv

怎么调用啊?

**Comment by sunrisewestern** [comment]
@Noah1995 如果是mac的话可以试试我这个AppleScript App. https://github.com/sunrisewestern/mmpv

**Comment by sunrisewestern** [comment]
<img width="779" alt="cat-catch-ss" src="https://github.com/user-attachments/assets/0cbfd074-32b1-467a-b95c-cd8fe76811a3">

**Comment by Noah1995** [comment]
> @Noah1995 如果是mac的话可以试试我这个AppleScript App. https://github.com/sunrisewestern/mmpv

不是苹果的,
那[Play-With-MPV](https://github.com/LuckyPuppy514/Play-With-MPV)是怎么调用的
不过Play-With-MPV不能所有视频都调用
只能匹配网站

**Comment by Noah1995** [comment]
> 能调用potplayer 是利用了他的伪协议功能 "potplayer://" mpv 认为伪协议不安全，没有伪协议功能。所以暂时没办法调用mpv播放器。

[Play-With-MPV](https://github.com/LuckyPuppy514/Play-With-MPV)是怎么调用的

**Comment by sunrisewestern** [comment]
@Noah1995  windows 可以看看这个 https://github.com/akiirui/mpv-handler

**Comment by Noah1995** [comment]
> @Noah1995 windows 可以看看这个 https://github.com/akiirui/mpv-handler windows 可以看看这个 https://github.com/akiirui/mpv-handler windows 可以看看这个 https://github.com/akiirui/mpv-handler

好吧看起来有点复杂没看懂...
有空再研究一下把
