### ISSUE TITLE
【请求】有声小说。能抓到音频，但是无法下载，无法捕获

### ISSUE THREAD

**Issue by zhangxuanluo** [xifangczy/cat-catch#347]
本人喜欢听本人喜欢听有声小说。能抓到音频，但是无法下载，无法捕获
网址：http://www.6yueting.com/play/22934cc5e2/3436

**Comment by xifangczy** [comment]
链接已经失效

**Comment by ousay** [comment]
![image](https://github.com/xifangczy/cat-catch/assets/25994346/c8fec77c-df49-4609-8151-9d8936d851e7)
下载链接需要替换一下

**Comment by zhangxuanluo** [comment]
> ![image](https://private-user-images.githubusercontent.com/25994346/326336802-c8fec77c-df49-4609-8151-9d8936d851e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzkzNTcsIm5iZiI6MTcxNDM3OTA1NywicGF0aCI6Ii8yNTk5NDM0Ni8zMjYzMzY4MDItYzhmZWM3N2MtZGY0OS00NjA5LTgxNTEtOWQ4OTM2ZDg1MWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA4MjQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZjRhYWIzYzZhMDc4ZWZmMWFkOWUwYjU1MmI4MWIzMGI1MmNlMDFmYmEwNDc5NTA5YzI2ODRlY2E0OWM4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vvUrz3QAU_DcbM1u9JQJQ-cQK5r33cZ3TRpTa3qLc4A) 下载链接需要替换一下

感谢解惑
