### ISSUE TITLE
西瓜视频获取视频花屏

### ISSUE THREAD

**Issue by luckingbird** [xifangczy/cat-catch#372]
西瓜视频中音视频分离的视频使用缓存获取，会出现10秒或20秒后都是花屏的内容

**Comment by xifangczy** [comment]
西瓜视频 什么页面需要用到 `缓存捕捉` ？
不是可以直接在线合并吗？

**Comment by lyanfu99** [comment]
我碰到了同样的问题, 正常下载或预览西瓜电影, 例如这个: 
https://www.ixigua.com/6569382994891506179
在 1分03秒 之后, 视频就变成了花屏, 音频也同样不正常.

**Comment by xifangczy** [comment]
查看 #380
