### ISSUE TITLE
下载西瓜电影花屏

### ISSUE THREAD

**Issue by lyanfu99** [xifangczy/cat-catch#380]
### 扩展版本号 extension version

v 2.5.2

### 浏览器

Microsoft Edge

### 浏览器版本号

版本 126.0.2592.81 (正式版本) (64 位)

### 涉及网址

https://www.ixigua.com/6569382994891506179

### 请详细描述问题

无法正常下载西瓜电影, 例如这个:
https://www.ixigua.com/6569382994891506179

下载的视频会在 01分00秒 左右开始变成花屏, 音频也同步出错. 

在猫抓界面中预览视频, 可以看到一样的花屏现象.

尝试切换不同的清晰度, 问题一样. 

[
![Snip240630_201336](https://github.com/xifangczy/cat-catch/assets/134820410/b21e22ba-0034-47dc-bfdb-8cf01ea547c2)
](url)

**Comment by xifangczy** [comment]
这网站的视频采用了 cenc-aes-ctr 加密。
避免纠纷，猫抓不会对单独某个网站解密，没找到通用的解决办法不会处理。

目前我已经把解密方法写到了别的网站，等个有缘人，写个油猴脚本吧。😏
