### ISSUE TITLE
详细信息

### ISSUE THREAD

**Issue by 727729853** [xifangczy/cat-catch#384]
以前是有当前播放的详细信息的。例如：seg-9.ts  seg-10.ts
更新后没有了。还是隐藏掉了？如何打开？

**Comment by xifangczy** [comment]
你是说什么页面？

**Comment by 727729853** [comment]
![image](https://github.com/xifangczy/cat-catch/assets/60378045/aa8cbf2c-4193-4008-8326-f50f1e5d2e7b)
以前能显示详细信息的。现在会显示一整个m3u8

**Comment by xifangczy** [comment]
设置里打开 ts格式就行了
