### ISSUE TITLE
Impossible to preview the video with vlc or potplayer and even by copying the url address of the detected streaming stream and putting it in vlc or potplayer, we get an error message there is no playback of the video contrary to 2 other extensions that manage to extract the playable url link in vlc or potplayer

### ISSUE THREAD

**Issue by trimechee** [xifangczy/cat-catch#385]
### 扩展版本号 extension version

2.5.2

### 浏览器

其他基于 Chromium 的浏览器

### 浏览器版本号

supermium, thorium, catsxp web browsers

### 涉及网址

https://french-anime.com/animes-vf/1443-kaiju-n8.html

### 请详细描述问题

Hello, thank you very much for this magnificent great awesome rare and super powerful amazing Cat-catch extension ! 🥇 💯 

Please i have a problem, I would like to please preview the streaming video and watch it via potplayer or vlc because my laptop is old and is not powerful and does not support all media codecs and often laggy streaming, so watch the video stream directly via vlc player or potplayer or smplayer or kikoplay or implay or moonplayer..... solves these problems of CPU power and unstable connection because the media player is lighter, ecological and does not use the fan battery and you can manually increase the buffer network cache in vlc, potplayer....so there is no lag even if our internet connection becomes weak and the fan is no longer noisy because no need for a heavy web browser.....

so preview the video with the native Cat-catcher player works but we cannot put it in full screen and in addition I would like to play the video with VLC or Potplayer without a heavy web browser which freezes my old laptop and without the need to wait the end of the download which can last a long time because the internet can be weak, I put the vlc, and potplayer option in the Cat-catcher preview settings, but I receive an error message in vlc or potplayer, I even copied the url address of the preview and the stream detected by Cat-catcher but the same thing, I receive error message in vlc and potplayer.....I even installed the extensions:

https://github.com/andy-portmen/external-application-button

https://github.com/andy-portmen/open-in-vlc

https://github.com/andy-portmen/open-in

https://github.com/andy-portmen/native-client

to send the links detected by Cat-catcher and the link of the preview url address to the media players but it doesn't work unfortunately :(

so please we hope our beloved Cat-catcher can either send the preview to vlc or potplayer without problem, or Cat-catcher gives us a m3u8 url address of the streaming video, for example on this site to put the ul address in vlc or potplayer or smplayer or moon player.....

https://french-anime.com/animes-vf/1462-demon-slayer.html

because I specify, I tried 2 video stream detection and video download extensions and I was able to copy the url address of the streaming video download link and send this link to vlc and potplayer and I was able to watch the streaming video without problems in vlc player and potplayer even when closing the web browser, so it seems the url address given by Cat-catcher differs from the url address given by these 2 extensions, thank you very much!

https://github.com/chandler-stimson/live-stream-downloader

https://github.com/puemos/hls-downloader

maybe if the problem persists, we hope please our beloved Cat-catcher can give if possible  an option to show the temporary folder where the video is being downloaded so we can playback the part being downloaded with vlc or potplayer , because I tried to download the video and Cat-Catcher managed to download the video but I don't like to wait for the end of the download to play the video because the download can take a long time and I checked if there is a temporary file hidden in the download folder while downloading the video but I found nothing even though I activated the option to show hidden files in Windows, and we hope for an option to set the number of threads during the download, because I hope to set the number of threads=1 to be able to preview the downloaded part, thank you very much :)

**Comment by xifangczy** [comment]
Hello, I have checked other extensions and the results are consistent, with the URLs being the same.

PotPlayer cannot preview, probably because the website has "referer" verification. The good news is that PotPlayer supports the setting of referer parameters, and it even supports URL Protocol.

You just need to change `potplayer://${url}` to `potplayer://${url}/referer=${referer}`

**Comment by xifangczy** [comment]
Which program can be called depends on whether the program has implemented the URL Protocol. As far as I know, VLC does not have this. You should propose this to the VLC community, not to cat-catch
