### ISSUE TITLE
为何使用v2rayN等科学上网工具后无法获取YouTube等外网视频

### ISSUE THREAD

**Issue by mg0209** [xifangczy/cat-catch#39]
国内一切嗅探正常，国外的不行，包括YouTube不行，好像没有地方设置代理

**Comment by xifangczy** [comment]
和代理没关系。
被google下架后 为了再上架主动屏蔽了youtube相关网站
[background.js#L53](https://github.com/xifangczy/cat-catch/blob/de051f7d2110ab0849a382f30fbe572ad84aae0a/js/background.js#L53)

另外 youtube猫抓是没办法的，目前猫抓还没主动抓取的功能，未来.... 大概... 也许会加上吧🙄
