### ISSUE TITLE
在猫抓 M3U8解析器页面勾选上下载完自动关闭页面，没能下载就关闭了

### ISSUE THREAD

**Issue by Jason-233** [xifangczy/cat-catch#393]
### 扩展版本号 extension version

2.5.2

### 浏览器

Microsoft Edge

### 浏览器版本号

126.0.2592.56

### 涉及网址

https://hianime.to/watch/berserk-1997-103?ep=3140

### 请详细描述问题

rt,我之前感觉跟xdown劫持浏览器下载有关，重新设置了不接管浏览器小于300MB文件的下载，xdown不弹窗了，可是浏览器自带下载就偶尔会没反应，解析页面就直接关闭了。有在后台标签页，也有在前台发生这种现象。我试过先勾选在点合并下载，反过来也一样，都发生过这个bug。

**Comment by xifangczy** [comment]
惊了 xdown 为什么会监听blob: 下载 实在不明白。

我会尝试下绕过这些接管下载的扩展或软件。
