### ISSUE TITLE
Disaster catastrophe : impossible to download, network error in https://ffmpeg.bmmmd.com/

### ISSUE THREAD

**Issue by trimechee** [xifangczy/cat-catch#399]
### 浏览器

其他基于 Chromium 的浏览器

### 浏览器版本号

Catsxp 127

### 涉及网址

https://v5.voiranime.com/anime/jojo-no-kimyou-na-bouken-stardust-crusaders-vf/jojos-bizarre-adventure-stardust-crusaders-02-vf/

### 请详细描述问题

Hello, i said our beloved Cat-catch is the most powerful tool in the world for downloading videos and that's the truth because Cat-catch managed to download videos that other open-source extensions failed to do especially with the recent modification of the protection and defense mechanism of streaming sites, but today in the afternoon, a strange thing happens, Cat-catch downloads the small fragments of this streaming video:

https://v5.voiranime.com/anime/jojo-no-kimyou-na-bouken-stardust-crusaders-vf/jojos-bizarre-adventure-stardust-crusaders-02-vf/

 then a new window opens in:

https://ffmpeg.bmmmd.com/

and I can preview the video and I click on the download button but I receive a "network error" message even though I am connected to the internet! I try again, same failure, so I redownload the video by setting the thread number 1 instead of 6 and I get the same "network error" error message!

I activated the catsxp developer mode and activated the collect errors option maybe it can help Mr @xifangczy  to fix this problem, maybe the website has blacklisted my IP address because I downloaded several videos, I will try turning off my router and try again tomorrow......

for the moment, even if I don't like using open source extensions, I tried with:

https://www.hlsloader.com/

and it works ! I was able to download the video but I will try to download other videos to see if the network error problem reappears, and we hope our beloved Cat-catch will solve this problem otherwise I would no longer be able to watch any videos on my laptop of 2012, thank you very much!

**Comment by xifangczy** [comment]
Check the error screenshot

**Comment by xifangczy** [comment]
The issue with ffmpeg.bmmmd.com has been fixed.
