### ISSUE TITLE
请问最新的2.5.3怎么使用谷歌浏览器和edge浏览器下载都安装不了

### ISSUE THREAD

**Issue by lpxks** [xifangczy/cat-catch#405]
![image](https://github.com/user-attachments/assets/74180b8d-3911-46b1-b0b9-c9ac932fe7e6)

**Comment by xifangczy** [comment]
已经上传到扩展商店，等待审核。edge已经通过了 可以更新到2.5.3
chrome 应该还要等一两天。

**Comment by lpxks** [comment]
> 已经上传到扩展商店，等待审核。edge已经通过了 可以更新到2.5.3 chrome 应该还要等一两天。
好的 谢谢

**Comment by lpxks** [comment]
> 已经上传到扩展商店，等待审核。edge已经通过了 可以更新到2.5.3 chrome 应该还要等一两天。

好的 谢谢
