### ISSUE TITLE
预览窗口无法全屏观看

### ISSUE THREAD

**Issue by 775405984** [xifangczy/cat-catch#408]
### 扩展版本号 extension version

2.5.3

### 浏览器

Microsoft Edge

### 浏览器版本号

126.0.2592.113

### 涉及网址

https://live.healnoc.com/live/page/71852578

### 请详细描述问题

![PixPin_2024-07-20_21-53-06](https://github.com/user-attachments/assets/0fb09f19-8442-4be8-af70-eaefc89a1d7c)

预览界面全屏按钮无效

**Comment by xifangczy** [comment]
这是正常的
全屏后 扩展页面会被浏览器收回 视频就没办法继续播放了。
你可以更新到最新的2.5.3 有弹出模式。在弹出模式内可以全屏。
