### ISSUE TITLE
合并下载B站视频文件名变成output

### ISSUE THREAD

**Issue by DuoLoLo** [xifangczy/cat-catch#411]
### 扩展版本号 extension version

v2.5.3

### 浏览器

Google Chrome

### 浏览器版本号

版本 126.0.6478.183（正式版本） （64 位）

### 涉及网址

https://www.bilibili.com/

### 请详细描述问题

之前合并下载还能自动改名成网页标题，最近合并下载只会命名为output.mp4

**Comment by xifangczy** [comment]
已修复。
