### ISSUE TITLE
为什么m3u8下载的片段打不开呢？

### ISSUE THREAD

**Issue by tb0668** [xifangczy/cat-catch#42]
https://awsstc.r18.com/r18/st1:blWzIh+iwgYbVdODDyKFRt9R1Xp57LglOgQOjMpQmawCJZo-Z+oB1fJVkukuTnlzQ86tGvDSMcuOpn6S0CudhQ==/-/cdn/media_b6000000_24.ts

**Comment by xifangczy** [comment]
因为媒体加密了... 你需要m3u8下载器去下载并合并。
