### ISSUE TITLE
Add a video quality indicator by adding feature "probe each stream found during the analysis (probe limit per stream (milliseconds) : 300

### ISSUE THREAD

**Issue by trimechee** [xifangczy/cat-catch#421]
Hello, in Cat-Catch settings, it will be great to have option "download the video with the lowest quality", however, for example on this site :

https://v5.voiranime.com/anime/kimetsu-no-yaiba-4-vf/kimetsu-no-yaiba-4-08-vf/

Because the extension always shows me 2 m3u8 streams, usually after experimenting I can figure out which of the 2 streams offered is the stream with the worst video quality and remember the name of the stream with the worst video quality.....but i can make mistake  and download a stream that has the highest quality.....

 i have an old laptop, old hard drive, not very powerful connection, so it is important for me and probably for many other people not to make a mistake and to be able to easily download the video with the worst quality to preserve our bandwidth, time, hard drive durability, battery, energy.....

and so it will be great please to add a video quality indicator on the m3u8 streams, maybe by adding an option like the one in the 3DYD youtube source plugin which has an option: "probe each stream found during the analysis (probe limit per stream (milliseconds) : 300 to detect the video quality and automatically display the desired video quality, thank you very much !

https://ys.3dyd.com/

**Comment by hsmaocn** [comment]
In the previous version of Cat-Catch, users could directly access and choose the "main file" (usually named as index.m3u8) from the M3U8 format video files, thereby manually selecting different quality video streams.

**Comment by hsmaocn** [comment]
In the current version of Cat-Catch (2.5.3), users can access and select the "master file" directly from a video file in M3U8 format (usually named index.m3u8, but sometimes it's not that simple, e.g.: 2eeoSCgcNrtZLHV8.m3u8, which is the name of a video file in an X (the original tweet). So you need to pay special attention. But most of the time it's the first link grabbed) so that you can manually select different quality video streams.

**Comment by hsmaocn** [comment]
![01](https://github.com/user-attachments/assets/b92c1a63-dee7-48ee-84ad-a6950ed32b03)
![02](https://github.com/user-attachments/assets/5822c022-e6de-42c5-99a4-0bd78a9ddc72)

**Comment by hsmaocn** [comment]
> 哦，非常有启发性和趣味性！非常感谢您的宝贵帮助和重要建议，先生！💯 🥇

You're welcome, this is what community norms should look like.
