### ISSUE TITLE
Add special support specific to Brave browser (or Catsxp browser) by requesting admission to their special list of extensions integrated by default in brave browser !

### ISSUE THREAD

**Issue by trimechee** [xifangczy/cat-catch#431]
Hello, Brave browser (and Catsxp browser which seems based on open-source brave browser) defies the mastodon google and keeps the support of manifest v2 provided that developers continue to update their manifest V2 extensions despite the manifest V 3 apocalypse, and brave browser has found a trick to keep manifest V2 extensions alive : brave team has integrated a special section in brave browser settings called "manifest V2 extensions" and brave team has selected 4 manifest V2 extensions integrated by default in brave browser like the famous ad blocker ublock origin ! 

and so to encourage brave team to keep alive the manfest v2 which is rare after the chromium apocalypse manfest V 3, and in the optics that google will perhaps make the manifest v3 even more restrictive or google will censor extensions .....

we hope please our beloved Cat-catch will make in the future a request to brave browser team to be included by default in the pre-selected list of manifest V2 extensions and to be integrated by default in brave browser or catsxp browser because Cat-catch is vital essential and will make brave browser more captivating for users especially if the firefox extension has kept the manfest V2 and we know firefox uses the same web extension technology as chrome so maybe the firefox extension of Cat-catch has remained in manifest V2 and compatible with brave browser or catsxp browser, because brave is very popular and i think brave could become more popular than chrome because brave keeps the manifest V2 and has other unique features like bittoreent streaming support ......

Thank you very much !

**Comment by xifangczy** [comment]
关于v2还是v3的问题 不再讨论。cat-catch未来都将以v3继续更新。是否继承到浏览器 也不是我们能做决定的。

The issue of whether to use v2 or v3 will not be discussed any further. Cat-catch will continue to be updated with v3 in the future. Whether it is integrated into the browser is not a decision we can make.

**Comment by trimechee** [comment]
"Whether it is integrated into the browser is not a decision we can make." :  i noticed that there is a special version of Cat-catch that lacks some features and options and cat catch is natively integrated into Catsxp browser, your compatriots catsxp developers got your permission to modify Cat-catch (because the cat catch integrated into catsxp is different from the official cat catch) ? 

and catsxp browser got your explicit permission to integrate a modified cat catch version into catsxp? i am not criticizing catsxp, it is good browser and  it is via catsxp that i discovered cat catch
