### ISSUE TITLE
Conflict of Automatically Close Page After Download of section "Downloader" and also section " M3U8 Parser"=bug=option "Automatically Close Page After Download " is always disabled even i enable it in "Downloader "and "M3U8 Parser" 

### ISSUE THREAD

**Issue by trimechee** [xifangczy/cat-catch#435]
### 扩展版本号 extension version

2.5.4

### 浏览器

其他基于 Chromium 的浏览器

### 浏览器版本号

127

### 涉及网址

https://v5.voiranime.com/anime/kenpuu-denki-berserk-vf/berserk-1997-01-vf/

### 请详细描述问题

Hello, in Cat-catch settings, when I activate Automatically Close Page After Download in the "Downloader" section and also in the "M3U8 Parser" section, always when the M3U8 Parser page is displayed and starts downloading the small fragments, always the "Automatically Close Page After Download" box is disabled by default while Automatically Close Page After Download should be enabled by default, maybe there is a conflict between the 2 settings that have the same option between the Downloader and the M3U8 Parser and we hope this bug will be fixed please, thank you !

**Comment by xifangczy** [comment]
2.4.3
[Changed] Settings changed on the m3u8 Parser and Downloader pages will not be saved. All settings changes are unified to the extension settings page.

**Comment by trimechee** [comment]
I fixed this problem  by disabling "Automatically Close Page After Download" of section "Downloader" and by enabling only "Automatically Close Page After Download of section "M3U8 parser" , so now the option " Automatically Close Page After Download " is alaways enabled in m3u8 parser and no more automatically disabled in M3U8 parser
