### ISSUE TITLE
新下载器（概率性）无法完成合并下载功能

### ISSUE THREAD

**Issue by DCxDESIGN** [xifangczy/cat-catch#440]
### 扩展版本号 extension version

2.5.4

### 浏览器

Microsoft Edge

### 浏览器版本号

128.0.2739.5

### 涉及网址

https://www3.nhk.or.jp/sports/olympics/schedules/

### 请详细描述问题

理论上来说这应该是一个老 bug 【。】我记得以前某一版本说修复了，但还是会发生，区别在于以前是旧的和新的都会概率性出问题，现在我暂时是在新下载器会遇到这个问题，旧的暂时没有碰上

重现方式：点开扩展按钮，找到 m3u8 条目，进入解析界面，下方选项的“另存为”勾不勾选都不影响，为了方便排查可以只勾选“新下载器”，然后选择“合并下载”，分块下载完成进入合并状态，然后就不动了，浏览器不会弹出下载框

我主力浏览器是用傲游（基于 Chromium），为了测试这个问题也试过用 Edge，对于我上面“涉及网址”给出的链接页面下所有「見逃し」的视频（需要日本线路），问题可以 100% 重现，意即只要勾选了“新下载器”就必定会分块下载完成后没有后续弹窗，而不勾选就可以顺利弹窗完成下载

另外，我给的这个网站是用了 AES-128 加密，但我平常在别的没有加密的视频站点也会概率性遇到此问题，因此我认为应当和是否加密没有关系

**Comment by trimechee** [comment]
yesterday i install maxthon, because maxthon has 32 bits version for windws 7, and i was disappointed that maxthon uses chromium version 109 while the current stable version of chromium is 127, try to contact maxthon team to fix this serious problem

**Comment by DCxDESIGN** [comment]
> yesterday i install maxthon, because maxthon has 32 bits version for windws 7, and i was disappointed that maxthon uses chromium version 109 while the current stable version of chromium is 127, try to contact maxthon team to fix this serious problem

As far as I know, Maxthon decided to stop updating the kernel to maintain support for Windows 7 precisely because version 109 is the last Chromium version that supports Windows 7.

**Comment by trimechee** [comment]
it is dangerous to use chromium 109 because there may be security flaws, recently a security flaw affected recent versions of chromium browsers and it was patched....so chromium 109 could not benefit from this important patch, right?

before my computer crashed, I installed maxthon for windows 10 and maxthon uses chromium 109 even in windows 10 os so I don't think it's about windows 7 support, in addition to web browsers like thorium legacy, supermium, yandex, catsxp....are compatible with windows 7 32 bits and use a recent chromium 124 lts.....I uninstalled maxthon while waiting for their technical team to reassure us that there are no security vulnerabilities compatibility using an old chromium ....and maxthon makes their video downloader paid, I no longer see the point of using maxthon which has an old chromium

**Comment by trimechee** [comment]
@DCxDESIGN The version of chromium is important to donwload videos, in recent changelog of Cat-catch, it says :"[Changed] Changed from storage.local to storage.session to reduce IO errors that could cause the extension to be unusable. (Requires Chrome 104 or above) "

**Comment by xifangczy** [comment]
经过漫长的等待(我jp节点很慢) 测试几个 都正常。。。我发现这些视频文件似乎很大 你查看是否内存不足。请尝试使用 边下边存功能。

**Comment by DCxDESIGN** [comment]
> it is dangerous to use chromium 109 because there may be security flaws, recently a security flaw affected recent versions of chromium browsers and it was patched....so chromium 109 could not benefit from this important patch, right?
> 
> before my computer crashed, I installed maxthon for windows 10 and maxthon uses chromium 109 even in windows 10 os so I don't think it's about windows 7 support, in addition web browsers like thorium legacy, supermium, yandex, catsxp....are compatible with windows 7 32 bits and use a recent chromium 124 lts.....I uninstalled maxthon while waiting for their technical team to reassure us that there are no security vulnerabilities compatibility using an old chromium ....and maxthon makes their video downloader paid, I no longer see the point of using maxthon which has an old chromium

I am just a user, not a member of the development team of MX. I use it just because I've used it for about 20 years, and I use Chrome and Edge as well. There's no need to explain to me why Maxthon sucks and why I should stop using it.

Additionally, I'm not sure how the browsers you mentioned manage to support Windows 7 while using the latest Chromium version. I only know that Maxthon uses a single version of the core and therefore chose to stick with an older version. You are not the only one complaining about this, but if the development team does not take action, there's nothing I can do about it.

> And I think the Chromium has nothing to do with this issue because it's the same in the latest Edge.

Again, please note this I mentioned before, the latest Edge has the same issue. That's why I said it's nothing to do with the Chromium, at least for this issue.

**Comment by DCxDESIGN** [comment]
> 经过漫长的等待(我jp节点很慢) 测试几个 都正常。。。我发现这些视频文件似乎很大 你查看是否内存不足。请尝试使用 边下边存功能。

我的内存是 32G，应该不至于……吧（我屏幕右侧一直有监控指示器，应该是没有满的

而且我有试过那种超大的文件，直接把我的存储盘挤满了的那种，我印象里它会直接报错而不是卡住不动【

边下边存我没有用过，我之后会试试，但我觉得这个问题应该还是有更好的解决方案。。

**Comment by DCxDESIGN** [comment]
> 经过漫长的等待(我jp节点很慢) 测试几个 都正常。。。我发现这些视频文件似乎很大 你查看是否内存不足。请尝试使用 边下边存功能。

我刚才在傲游和 Edge 都试了一下：
· 即使是小文件（如 100-200MB 的纯音频流），只打开“新下载器”就必然会下载完卡住，不弹出下载文件框；
· 如果打开“边下边存”，因为是开始下载的一瞬间就弹出下载文件框，所以可以正常完成下载，应该确实是一个解决方案；
· 甚至之前我只开“新下载器”的时候下完但卡住的文件块，在打开边下边存再次下载的时候，都是直接读的缓存，没有再次联网重新下载，也可以作为这个 bug 的一个挽救措施

**Comment by trimechee** [comment]
Yes i know it is edge probelm, i just advice you :) yes supermium browser and thorium legacy browser and yandex and catsxp 32 bits use recent chromium version, they invent and develop chromium for windows 7 32 bits, i am using them with no problem and bug, ony i have some problems wit catsxp,  you can test by tourself, supermium keeps manifest V2 so adblockers like ubock origin  remain strong,  yesterday i even fond new browsers based on the recent firefx 129 whereas mozilla make only firefox esr 115 for windows 7, i install them and they work perfectly : 

https://github.com/Eclipse-Community/r3dfox

https://github.com/twilight-software/luminafox

https://github.com/Alex313031/Mercury-Win7

palemoon and basilisk browsers are also compatible with windows 7 32 bits and they are frequently updated

**Comment by trimechee** [comment]
Thank you :) I don't want to be unfair with @maxthon,  if Maxthon adds the chromium security patches, then no problem, I saw the chagelog and I was surprised that maxthon is actively updated despite the old chromium !! I enjoyed using maxthon all these years, it's a good browser but when the video downloader didn't work anymore, I abandoned this web browser for coc coc browser, coc coc browser for windows 7 also uses chromium 109 and it is abandoned because there is no more chromium for windows 7 .... but coc coc browsers for windows 10 use the new chromium ....

**Comment by DCxDESIGN** [comment]
> Thank you :) I don't want to be unfair with @maxthon, if Maxthon adds the chromium security patches, then no problem, I saw the chagelog and I was surprised that maxthon is actively updated despite the old chromium !! I enjoyed using maxthon all these years, it's a good browser but when the video downloader didn't work anymore, I abandoned this web browser for coc coc browser, coc coc browser for windows 7 also uses chromium 109 and it is abandoned because there is no more chromium for windows 7 .... but coc coc browsers for windows 10 use the new chromium ....

The newly added Video Downloader in MX actually didn't behave as it advertise, in my opinion.

But fortunately, we have Cat-Catch :-)

**Comment by trimechee** [comment]
Yes indeed Cat-catch is saver life ! 💯

**Comment by DCxDESIGN** [comment]
> 出现bug时 请f12 查看控制台 是否有错误输出

我似乎发现了问题所在，我在猫抓设置的“其它设置”里勾选了 **使用自定义文件名保存文件(默认为网页标题)**，这样就可以重现了，F12 控制台里当文件下载完成后会提示 `m3u8.html:1 Unchecked runtime.lastError: Invalid filename` 

因为我平常都是开着这个选项的所以一时间没想到会是这个原因

当我在设置里把这个选项关闭，问题就不会出现了；如果在解析页面填入了自定义文件名，问题也不会出现

那么现在的问题就变成了为什么这个网站的标题作为文件名 （例如我回复这条时使用的视频页面 https://www3.nhk.or.jp/sports/olympics/video/detail.html?scheduleSessionId=a05d7daa-a705-a219-38aa-b6def92c0c78 ，标题为 `パリ五輪2024閉幕 日本選手団旗手は やり投げ北口榛花とブレイキンShigekix(半井重幸) ／ ロサンゼルス大会への引き継ぎにも注目 | 動画配信 | NHK パリ オリンピック2024` ）就会直接报错，是因为用了管道 `|` 符号吗，如果是的话可不可以加一道前置的检测和处理，遇到可能会报错的标题字符就把它去掉或者更换成安全的字符

**Comment by DCxDESIGN** [comment]
> 非常感谢你的测试。由于windows文件名不允许使用`|` 字符。所以chrome download api 下载错误。之前下载器出现过这bug 忘记了m3u8解析器内也存在。 bug已经处理。等待下个版本发布。

好的，非常感谢，静候新版
