### ISSUE TITLE
下载失败，进度不涨了

### ISSUE THREAD

**Issue by xxxqq55** [xifangczy/cat-catch#450]
### 浏览器

Microsoft Edge

### 请详细描述问题

![屏幕截图 2024-08-16 225117](https://github.com/user-attachments/assets/a43a64b6-5d32-4dba-89fb-4363f04a0757)
我现在该怎么办，现在浏览器显示进度不涨了，而下面页面显示都快下完了，

**Comment by xxxqq55** [comment]
我现在不敢点下面停止下载，会不会直接白下了呀

**Comment by xifangczy** [comment]
有可能是中间某个切片没有下载完成 或者 下载失败。中间缺少一个就会一直等待。

**Comment by xxxqq55** [comment]
> 有可能是中间某个切片没有下载完成 或者 下载失败。中间缺少一个就会一直等待。

发现了，有个切片下了点就一直不动，也不显示下载失败，这有解决办法吗，我好像其他下载里也一直碰到

**Comment by xifangczy** [comment]
> 发现了，有个切片下了点就一直不动，也不显示下载失败，这有解决办法吗，我好像其他下载里也一直碰到

点击下停止下载 再点击重新下载

cloudflare的东西国内连接丢包严重 最好挂梯子下
