### ISSUE TITLE
希望能支持rplay这个网站的解析

### ISSUE THREAD

**Issue by aawwsslll** [xifangczy/cat-catch#454]
rt，格式是hls，似乎有加密，下面这个视频举例，需要注册一个号登录关注该博主才能观看，
然后试了好多个插件都解析不了这个视频，目前好像只能录制视频处理了。
https://rplay.live/play/66c0df0e1460f76f52ad282b/

**Comment by xifangczy** [comment]
`深度搜索` 可以 测试下来获取的最后一条资源 是最高分辨率且能正常下载的资源。

**Comment by aawwsslll** [comment]
> `深度搜索` 可以 测试下来获取的最后一条资源 是最高分辨率且能正常下载的资源。
> 
> 因为这网站的m3u8链接似乎是一次性的，被网站加载后链接就失效了。所以传统方法无法下载。

确实可以。就是只能用自带软件下载了，无法调用其他软件。先这么用吧。我关了。
