### ISSUE TITLE
快取捕捉失效

### ISSUE THREAD

**Issue by ericcheng26** [xifangczy/cat-catch#455]
### 扩展版本号 extension version

2.5.4

### 浏览器

Google Chrome

### 浏览器版本号

127.0.6533.120

### 涉及网址

https://drive.google.com/file

### 请详细描述问题

過往在google drive上的影片可以透過快取捕捉來下載，會出現一個窗口來控制快取捕捉的功能，但現在完全消失了

**Comment by xifangczy** [comment]
感谢提交bug
下个版本修复。

google drive 可以添加正则获取
`(^https://.*\.drive\.google\.com\/videoplayback\?.*)&range=.*` 后缀填写 `mp4`
