### ISSUE TITLE
发送到aria2时可否支持自定义目录

### ISSUE THREAD

**Issue by tonyzzp** [xifangczy/cat-catch#460]
发送请求到aria2 rpc时能否支持自定义下载目录。

**Comment by tonyzzp** [comment]
我的意思是指向aria发送下载请示时指定一个目录前缀，手动填写。

因为我的aria还需要下载别的内容，我希望通过抓猫下载的不同类型文件独放到不同的子目录。

**Comment by tonyzzp** [comment]
addurl方法好像支持传入dir参数。

**Comment by xifangczy** [comment]
emmm 子目录到是可以做到。考虑下怎么添加吧

**Comment by tonyzzp** [comment]
我又看了文档，是直接指定绝对 路径。


https://aria2.github.io/manual/en/html/aria2c.html#id5


希望可以在设置里给不同类型文件设置不同的目录

**Comment by xifangczy** [comment]
可以打开 `使用自定义文件名保存文件(默认为网页标题)` 选项 
然后在 `替换标签 - 自定义保存文件名` 设定子目录。
例如 `${ext}/${title}.${ext}` or `${title}/${fullFileName}`  都是可以的。
