### ISSUE TITLE
解析网站后调用按钮能传递添加的密匙参数

### ISSUE THREAD

**Issue by aawwsslll** [xifangczy/cat-catch#463]
** 详细描述想要添 加/修改/增强 的功能 **
如下图，我这边手动复制base64的key到输入框中，再预览命令是自动在后面加上了key.
但是点击调用m3u8dl或者调用re时这两个软件时，添加的密匙key都没传递过去，导致每次我都需要复制key后再查看预览命令，复制链接，再打开cmd命令才能下载。希望能支持调用时能把预览命令的链接参数都传递过去下载。

截图网址：https://nicochannel.jp/mochimochiamachi/video/sme9rGm8XSBRpaVJXiXeTc6i
<img width="983" alt="屏幕截图 2024-08-30 115020" src="https://github.com/user-attachments/assets/f2590e7e-8c4d-4c16-824f-1de77818540c">

**Comment by xifangczy** [comment]
这个页面一直在加功能 现在操作逻辑确实有点问题。

`调用` 按钮不会被 `加入设置参数` 选项影响，只会影响 `调用m3u8DL`按钮

只要填好自定义key 勾选上 `加入设置参数` 之后 点击 `调用m3u8DL` 会自动把key带过去的。

有一点要注意
`加入设置参数 ` 会自动把页面上的设置 比如 下载线程 下载范围 自定义文件名 自定义KEY 等等 添加到参数内。但是以RE还是CLI方式添加，是以 `设置` - `URL Protocol m3u8dl` 你选中的选项决定的(默认是 N_m3u8DL-CLI)

所以如果你调用的是N_m3u8DL-RE 但是没在`URL Protocol m3u8dl` 设置成RE 那添加的参数会有问题RE无法识别。检查下是不是这个问题导致的？

**Comment by aawwsslll** [comment]
> 这个页面一直在加功能 现在操作逻辑确实有点问题。
> 
> `调用` 按钮不会被 `加入设置参数` 选项影响，只会影响 `调用m3u8DL`按钮
> 
> 只要填好自定义key 勾选上 `加入设置参数` 之后 点击 `调用m3u8DL` 会自动把key带过去的。
> 
> 有一点要注意 `加入设置参数 ` 会自动把页面上的设置 比如 下载线程 下载范围 自定义文件名 自定义KEY 等等 添加到参数内。但是以RE还是CLI方式添加，是以 `设置` - `URL Protocol m3u8dl` 你选中的选项决定的(如果是禁用 默认是 N_m3u8DL-CLI)
> 
> 所以如果你调用的是N_m3u8DL-RE 但是没在`URL Protocol m3u8dl` 设置成RE 那添加的参数会有问题RE无法识别。检查下是不是这个问题导致的？

选项决定的(如果是禁用 默认是 N_m3u8DL-CLI)，以前默认禁用时，点调用m3u8DL按钮报错，提示base64数据有问题，选择
N_m3u8DL-CLI后，加入base64参数就能正常调用下载了。暂时先这样用吧，希望后续re也能支持加入自定义参数，目前你看我的
截图其实预览命令的链接格式是对的，我复制到re里也能下载，就是调用没有生效加入设置参数。
