### ISSUE TITLE
htm file instead of mp4 video from uqload platform

### ISSUE THREAD

**Issue by trimechee** [xifangczy/cat-catch#465]
### 扩展版本号 extension version

2.5.4

### 浏览器

其他基于 Chromium 的浏览器

### 浏览器版本号

128

### 涉及网址

https://uqload.ws/uxv9sm9tk4s0.html

### 请详细描述问题

Hello, I get htm file instead of mp4 video when downloading videos from uqload platform :

https://uqload.ws/uxv9sm9tk4s0.html

4th media player in this site : 
https://french-anime.com/animes-vf/844-orient.html

**Comment by trimechee** [comment]
I test the same uqload video with Live stream dowloader :  

https://github.com/chandler-stimson/live-stream-downloader 


i can donwload uqload video with mp4 extension without bug.....

**Comment by xifangczy** [comment]
![20240901062116](https://github.com/user-attachments/assets/28a759da-aac7-4cd8-a6d8-f37d41ec8a2f)

Use `downloader` to download. If `Error: Service Temporarily Unavailable 503` appears, it means the requests are too frequent. Refresh the `downloader` page

**Comment by trimechee** [comment]
Great !! Thank you so much for your precious help :) 💯 🥇
