### ISSUE TITLE
yandex浏览器兼容问题

### ISSUE THREAD

**Issue by komorebi522** [xifangczy/cat-catch#47]
最近几个版本的猫抓已经提示与yandex browser 不兼容了.可惜

**Comment by komorebi522** [comment]
> 因为chrome 扩展的Manifest 计划在 2023 淘汰V2版本 https://developer.chrome.com/blog/mv2-transition/
> 
> 猫抓不得不升级到V3，这导致必须引用新API 新API至少需要 93 以上chromium内核. 大概是 yandex 使用的chromium内核太低...
> 
> 可以使用[1.0.16](https://github.com/xifangczy/cat-catch/releases/tag/1.0.16) 版本
> 
> 正在计划的2.0版 甚至需要 102内核版本



> 因为chrome 扩展的Manifest 计划在 2023 淘汰V2版本 https://developer.chrome.com/blog/mv2-transition/
> 
> 猫抓不得不升级到V3，这导致必须引用新API 新API至少需要 93 以上chromium内核. 大概是 yandex 使用的chromium内核太低...
> 
> 可以使用[1.0.16](https://github.com/xifangczy/cat-catch/releases/tag/1.0.16) 版本
> 
> 正在计划的2.0版 甚至需要 102内核版本

不啊，现在用的yandex内核已经更新到102了，不过没关系，用着1.0.16也行

**Comment by xifangczy** [comment]
目前yandex 内核在100 可以使用。但是源码加载会很麻烦，官方又用的是opera商店。。太小众了 不打算在opera上搞。。
