### ISSUE TITLE
M3U8-RE调用问题。

### ISSUE THREAD

**Issue by thisisjin** [xifangczy/cat-catch#474]
### 扩展版本号 extension version

2.5.2

### 浏览器

Google Chrome

### 浏览器版本号

124.0.2478.105

### 涉及网址

en.jable.tv

### 请详细描述问题

使用URLProtocol设置好了协议。
![image](https://github.com/user-attachments/assets/07902bba-45dc-441a-bdb6-feccc3268ef7)
猫抓的设置也也设置了调用M3U8-RE
![image](https://github.com/user-attachments/assets/0fbf8b9c-54a3-4b55-ab78-17cb4a3b6c74)
但是在视频嗅探的页面，点开猫抓，点击下载，会跳出M3U8-RE的界面然后秒消失。
我录屏逐帧观察，发现出现的界面跟直接双击M3U8-RE一样。
![image](https://github.com/user-attachments/assets/c8f40b17-575c-41a8-8a87-54658058fb21)
不知道是我哪里设置不对？？

**Comment by xifangczy** [comment]
RE和CLI的参数不一样 把下面的参数设置给改成RE的就行了 比如保存目录的参数是 `--save-dir`
具体查看 RE的参数
https://github.com/nilaoda/N_m3u8DL-RE?tab=readme-ov-file#%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0

**Comment by thisisjin** [comment]
尝试了更改参数，但似乎没啥作用，依然是点击下载后，出现窗口闪退，就像是没有把指令传送到m3u8re一样。有点费解@@

我上传一个GIF，你估计就能看到我的情况是什么了。
![Video_2024-09-14_100806](https://github.com/user-attachments/assets/ae689595-2d51-43c2-ad65-4b4e802679cb)

**Comment by thisisjin** [comment]
不好意思，根据参考文档替换示例后已解决。谢谢！
