### ISSUE TITLE
希望增加在VLC中打开的选项

### ISSUE THREAD

**Issue by huiyang-work** [xifangczy/cat-catch#48]
当前的potplayer选项很好用，但是VLC更强大和顺手，希望添加支持

**Comment by huanghaobaobao** [comment]
自定义岂不是更好😁

**Comment by xifangczy** [comment]
VLC在windows和mac OS我没看到有协议可以调用。目前除了ios版本有 `vlc-x-callback://` 协议
等VLC官方有了调用协议我会加上

自定义的话 需要你自己去注册协议 有这个能力的人 我觉得也应该会修改源码了... 那不是更自定义么🤣

**Comment by huanghaobaobao** [comment]
> VLC在windows和mac OS我没看到有协议可以调用。目前除了ios版本有 `vlc-x-callback://` 协议 等VLC官方有了调用协议我会加上
> 
> 自定义的话 需要你自己去注册协议 有这个能力的人 我觉得也应该会修改源码了... 那不是更自定义么🤣

哈哈，大佬辛苦了，2.0很牛，感谢！
