### ISSUE TITLE
edge最新版为什么没有新功能？

### ISSUE THREAD

**Issue by huanghaobaobao** [xifangczy/cat-catch#49]
edge 版本 103.0.1264.44 (正式版本) (64 位)，微软商店安装后还是1.0.28，这是咋回事？商店里显示已经是2.1.0了啊，chrome商店安装正常显示

**Comment by xifangczy** [comment]
扩展页面 `edge://extensions/` 左侧打开 `开发人员模式` 再点击右上角`更新`按钮
