### ISSUE TITLE
firefox抓取完毕合并下载时浏览器会卡住

### ISSUE THREAD

**Issue by cyfex** [xifangczy/cat-catch#492]
### 浏览器

Firefox

### 请详细描述问题

m3u8抓取合并下载，下载结束合并且保存时，整个浏览器会卡住，无法操作其他选项卡，有同步/异步的阻塞问题？

**Comment by cyfex** [comment]
还有在有些网站，通过猫爪插件点击下载嗅探到的mp4(此时调用浏览器自身下载)，也会超级卡，cpu占用140％，也是firefox的问题，chromium不会。

**Comment by cyfex** [comment]
又发现一个问题，还有在有些网站，通过猫抓嗅探mp4，无论在插件中调用浏览器直接下载，还是复制链接到地址栏下载，都会超级卡，firefox中task manager看一下cpu占用140％。此时，如果禁用掉猫抓，再复制链接进行下载，一切流畅。

这个问题chromium不存在。

firefox中这个下载过程是不是一直被猫抓监听着，导致反反复复拉爆了？

**Comment by xifangczy** [comment]
没有复现这个问题
是否有其他下载管理器的扩展。
