### ISSUE TITLE
调用m3u8的时候报错了  估计是标题有韩文的原因？

### ISSUE THREAD

**Issue by 727729853** [xifangczy/cat-catch#495]
### 扩展版本号 extension version

2.5.4

### 浏览器

Google Chrome

### 浏览器版本号

129.0.6668.71

### 请详细描述问题

调用m3u8的时候，报错了：
未经处理的异常System formatExceotion:
输入的不是有效的 Base-64字符串，
因为它包含非
Base-64字符、两个以上的填充字符

**Comment by xifangczy** [comment]
调用第三方下载软件吗？

**Comment by 727729853** [comment]
> 调用第三方下载软件吗？
N_m3u8DL-CLI-SimpleG.exe
以前可以调用的，试了下如果标题有数字和英文可以。韩文就不行了

**Comment by 727729853** [comment]
感谢，已解决！
