### ISSUE TITLE
Unchecked runtime.lastError: Error message : The page keeping the extension port is moved into back/forward cache, so the message channel is closed.

### ISSUE THREAD

**Issue by trimechee** [xifangczy/cat-catch#498]
### 扩展版本号 extension version

2.5.4

### 浏览器

其他基于 Chromium 的浏览器

### 浏览器版本号

129

### 涉及网址

extensions section of catsxp browser 

### 请详细描述问题

Hi, I specify that I did not encounter any bug or problem to download, but just to help Mr @xifangczy to fix possible problems, I activated the "error" section of the extensions and I note a mysterious persistent message when I open the extensions page of my web browser castxp:

"Unchecked runtime.lastError: The page keeping the extension port is moved into back/forward cache, so the message channel is closed."

we hope this is not a serious error that will impact the normal operation of downloads in the future :)

**Comment by xifangczy** [comment]
ignore this bug
