### ISSUE TITLE
多选下载M3U8无法使用m3u8dl:// 协议，使用了浏览器下载

### ISSUE THREAD

**Issue by Blackblock-inc** [xifangczy/cat-catch#504]
### 扩展版本号 extension version

2.5.5

### 浏览器

Microsoft Edge

### 浏览器版本号

129.0.2792.79

### 请详细描述问题

单个文件下载时可以调用，多选文件用下载所选按钮会使用浏览器下载这会导致下载的是M3U8文件而不是进行调用解密成MP4文件保存
多选下载的时候应该可以批量解密M3U8文件并转存，这是BUG还是？

**Comment by xifangczy** [comment]
是bug
没考虑到m3u8会有批量下载需求...
