### ISSUE TITLE
Planned future support of Flybird-m3u8downloader ? 

### ISSUE THREAD

**Issue by trimechee** [xifangczy/cat-catch#505]
Hi, this summer,  I remember discussion between Mr @xifangczy and Mr @youwen21 , and if i am right,  it seems Cat-Catch will add specific support for the magnificent Flybird-m3u8downloader which allows us to download large files and get rid of the 2Gb limit imposed by web browsers....so will Flybird-m3u8downloader be integrated into the settings of the magnificent Cat-Catch like m3u8DL RE?

**Comment by xifangczy** [comment]
[flybird-downloader](https://github.com/youwen21/flybird-downloader) 已经支持了 猫抓的数据发送。

The [flybird-downloader](https://github.com/youwen21/flybird-downloader) has already supported the data transmission of cat-catch.
