### ISSUE TITLE
Catsxp remove buil-in Cat-catch : dispute between catsxp and Cat-Catch ?! 

### ISSUE THREAD

**Issue by trimechee** [xifangczy/cat-catch#514]
Hi, I discover with surprise and sorrow the removal of buil-in Cat-Catch from catsxp browser by reading the changelog of the beta version, it's a shame because it's by digging in the advanced settings of catsxp that I discovered the existence of the great Cat-Catch, but I also noticed the version of Cat Catch included in catsxp lacks options and I asked Mr Xfangczy if he authorized catsxp to modify the original code of Cat-Catch.....

and so I wonder about the removal of cat catch from catsxp, was there a dispute between catsxp and cat-catch despite the fact that they are both Chinese? that's the question?

i can't ask the question
to catsxp because catsxp absurdly unfair didn't liked my request to enable the internal heavy ads blocker of chromium .....

so I myself do not have a good relationship with catsxp and I criticized them by opening an issue on github ..... :

obviously I am in solidarity with Cat-Catch in this matter and catsxp's behavior is unacceptable

[v4.10.3](https://www.123pan.com/s/vwsRVv-xnoxh)Beta-10

1.[*]Kernel upgrade:130.0.6723.48

2.[!]Some problems correction and detail optimization

3.[+]Open functions:playlist

4.[-]Remove built-in video sniffer extension

**Comment by xifangczy** [comment]
catsxp是否添加是他的自由 我们并没有争议。也许是因为视频网站版权施压，这不奇怪。

It is his freedom to add catsxp, and we have no dispute. Perhaps it's because of the pressure from video site copyrights, which is not surprising.
