### ISSUE TITLE
Add special heavy mode for advanced users : "Improved Media Detection" option, therefore we can temporarily enable this option, but after enablig this heavy mode, we turn it off again once the media has been detected !

### ISSUE THREAD

**Issue by trimechee** [xifangczy/cat-catch#517]
Hi, of course we understand that Mr Xifangczy is concerned that his magnificent extension is light and speed and does not consume a lot of cpu resources 💯 🥇 

but sometimes, there are some complex videos to detect and the standard normal detection does not work, or we just like preview the video with potplayer and we will close the heavy web browser, 

so my suggestion please is to add a special heavy mode for advanced users like in the open source extension "Live Stream Downloader", so we avoid tiring Mr Xifangczy  so that he finds us a regex rule for a specific site when a video is not detected :

"Improved Media Detection" option :

" This option improves the extension's ability to detect media in browser tabs by installing an additional network observer that monitors for links with video or audio mime types. However, this process can be resource-intensive, so I recommend only using it if you are experiencing issues with the media detection feature. You can temporarily enable this option, but make sure to turn it off again once the media has been detected." :

https://webextension.org/listing/hls-downloader.html#faq12 

Thank you so mch !

**Comment by xifangczy** [comment]
The function is already included
