### ISSUE TITLE
[css]popup.css样式文件中的某个下边框值过小,popup页会产生遮挡

### ISSUE THREAD

**Issue by WeaponJang** [xifangczy/cat-catch#52]
**bug描述**
.mediaList {
  margin-bottom: 30px;
}
上面的这个30px太小,有些网站的会被遮挡,比如酷狗直播的m3u8地址
margin-bottom: 30px;改成4rem尺寸比较合适
**浏览器**
- Chrome
- 103

**扩展**
 - 2.1.2

**安装方式**
- 官方扩展店

**涉及网址**
比较随机

**Comment by xifangczy** [comment]
试了很多分辨率 都没有复现这个问题

**Comment by WeaponJang** [comment]
> 试了很多分辨率 都没有复现这个问题

只在设备分辨率在1366*768以下的浏览器上有此问题,而且也不是每个站点都能复现,fanxing.com复现的概率大点.请注意这是设备分辨率,不是浏览器的尺寸

**Comment by xifangczy** [comment]
https://github.com/xifangczy/cat-catch/issues/57
浏览器字体设置过大导致按钮变高。2.2.1已修复这个问题。
