### ISSUE TITLE
爱奇艺qsv文件使用ffmpeg转MP4时，只生成了音频文件

### ISSUE THREAD

**Issue by Qxhonor** [xifangczy/cat-catch#521]
### 扩展版本号 extension version

v2.5.5

### 浏览器

Microsoft Edge

### 浏览器版本号

129.0.2792.89

### 涉及网址

https://ffmpeg.bmmmd.com/

### 请详细描述问题

爱奇艺qsv文件使用ffmpeg转MP4时，只生成了音频文件

**Comment by xifangczy** [comment]
这和在线ffmpeg没关系 qsv应该是自有加密的格式 ffmpeg无法处理
