### ISSUE TITLE
腾讯视频是彻底嗅探不到任何内容了

### ISSUE THREAD

**Issue by Eso3X** [xifangczy/cat-catch#522]
### 扩展版本号 extension version

v2.5.5

### 浏览器

其他基于 Chromium 的浏览器

### 浏览器版本号

Chromium 118.0.5993.159

### 涉及网址

https://v.qq.com/x/cover/mzc002004vakw66/n3567yjmfhn.html

### 请详细描述问题

![微信截图_20241016024933](https://github.com/user-attachments/assets/33d48feb-21a1-4ea0-ae08-2fff477b41c2)
不知道鹅厂是不是用了什么新的加密方式，嗅探出来就一个js脚本了....

**Comment by xifangczy** [comment]
![image](https://github.com/user-attachments/assets/b1ac6898-61b5-4026-b207-03f45115c78a)

**Comment by Eso3X** [comment]
> ![图像](https://private-user-images.githubusercontent.com/1239904/377712292-b1ac6898-61b5-4026-b207-03f45115c78a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NjQ0MzYsIm5iZiI6MTcyOTQ2NDEzNiwicGF0aCI6Ii8xMjM5OTA0LzM3NzcxMjI5Mi1iMWFjNjg5OC02MWI1LTQwMjYtYjIwNy0wM2Y0NTExNWM3OGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMjI0MjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWE3YmVmNzJlNjg0YTEyNmZhNTk3MmU0MDgzZDEyNGFiNDkxNGM1NTg3NThiZmY5OTU4MjYwMmEyODUyYzQ4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Zetqi_yZcuNJL0nWxInsqsJO0TdINy5zH1DEj1_7VPs)

感谢回复，终于找到原因了是广告插件把特定链接给屏蔽了
