### ISSUE TITLE
无法同时下载多个视频

### ISSUE THREAD

**Issue by venom8823** [xifangczy/cat-catch#531]
### 扩展版本号 extension version

版本2.5.5

### 浏览器

Microsoft Edge

### 浏览器版本号

版本 109.0.1518.140 (正式版本) (64 位)

### 涉及网址

所有网站都这样

### 请详细描述问题

多个猫抓页面同时下载时，最先下载完的页面会跳转到https://ffmpeg.bmmmd.com/转码，这一步骤的同时，会自动关闭其他还没下载完的猫抓页面，测试多次和多个网站都一样的情况。无法同时下载多个视频Orz

**Comment by xifangczy** [comment]
是m3u8解析器还是？

**Comment by venom8823** [comment]
是M3u8下载，刚才我又复现了一次这个情况：我同时打开两个M3u8下载，第一个先下载完成后，第一个下载页面关闭，浏览器页面打开ffmpeg转码，当转码完成  开始保存mp4文件时，（此时第二个M3u8下载还没完成），会关闭全部M3u8下载页面，这种情况导致只能每次下载一个M3u8视频。下面是https://ffmpeg.bmmmd.com/页面的运行记录：
加载FFmpeg中...
FFmpeg加载完成 ffmpeg core v0.12.6
等待接收媒体文件...请勿关闭本页面...
无需任何操作, 请耐心等待格式转换...成功后，自动下载文件
ffmpeg version 5.1.4 Copyright (c) 2000-2023 the FFmpeg developers
  built with emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.40 (5c27e79dd0a9c4e27ef2326841698cdd4f6b5784)
  configuration: --target-os=none --arch=x86_32 --enable-cross-compile --disable-asm --disable-stripping --disable-programs --disable-doc --disable-debug --disable-runtime-cpudetect --disable-autodetect --nm=emnm --ar=emar --ranlib=emranlib --cc=emcc --cxx=em++ --objcc=emcc --dep-cc=emcc --extra-cflags='-I/opt/include -O3 -msimd128' --extra-cxxflags='-I/opt/include -O3 -msimd128' --disable-pthreads --disable-w32threads --disable-os2threads --enable-gpl --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libopus --enable-zlib --enable-libwebp --enable-libfreetype --enable-libfribidi --enable-libass --enable-libzimg
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[mpegts @ 0xdea180] start time for stream 2 is not set in estimate_timings_from_pts
Input #0, mpegts, from 'memory1729997565142.ts':
  Duration: 00:13:40.70, start: 0.101000, bitrate: 3725 kb/s
  Program 1 
  Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn
  Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 181 kb/s
  Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Output #0, mp4, to 'xxxxxx.mp4':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 30 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 181 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
frame=24619 fps=9591 q=-1.0 Lsize= 361848kB time=00:13:40.60 bitrate=3612.3kbits/s speed= 320x
video:345573kB audio:15613kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.183352%
Aborted()
正在生成并下载文件 xxxxxx.mp4

**Comment by venom8823** [comment]
找到了一个解决方法，在未下载完成的m3u8页面，取消勾选这个选项“下载完自动关闭页面”，就可以避免这个问题。但是这个“下载完自动关闭页面”每次打开新的m3u8解析下载，会自动勾选，即使我在设置中关闭了所有的“自动关闭页面”的设置，也是一样会在新页面中自动勾选“下载完自动关闭页面”，这个怎么弄Orz
![QQ图片20241027111618](https://github.com/user-attachments/assets/d4a159b4-dc8a-45ac-b3e0-43c8409cbbb8)

**Comment by xifangczy** [comment]
感谢提交 已经定位到bug位置修复了。

另外 自动关闭问题 如果你开启了 `点击 下载按钮 使用m3u8解析器立即开始合并下载` 会加上自动关闭的选项。
想了下 确实不应该强行加上 下个版本取消这个设定。
