### ISSUE TITLE
Preview with potplayer works with firefox based browser but doesn't work with chromium based browser

### ISSUE THREAD

**Issue by trimechee** [xifangczy/cat-catch#534]
### 扩展版本号 extension version

2.5.6

### 浏览器

其他基于 Chromium 的浏览器

### 浏览器版本号

130

### 涉及网址

https://livetv.sx/frx/showvideo/1367251_real_madrid_barcelone/

### 请详细描述问题

Hi, preview with potplayer works with r3dfox based on the last firefox kernel for windows 7 OS but preview doesn't work with Catsxp browser based on the last chromium kernel for windows 7 OS : 

https://livetv.sx/frx/showvideo/1367251_real_madrid_barcelone/

**Comment by xifangczy** [comment]
这是potplayer的问题
chrome 130版本对自定义协议的更改导致。
所有关于 potplayer 预览的问题 都和该项目无关。

This is a problem with PotPlayer
Changes to custom protocols in Chrome version 130 have caused.
All issues related to potplayer previews are not related to this project.
