### ISSUE TITLE
m3u8流可否自动合并后下载，可选mp4这样的格式。

### ISSUE THREAD

**Issue by Ruling95** [xifangczy/cat-catch#537]
** 详细描述想要添 加/修改/增强 的功能 **
![image](https://github.com/user-attachments/assets/c0be4cd3-2359-4659-a533-30986564d700)
现在一个直播回放流媒体会分成很多，不知道咋合成一个文件。

**Comment by xifangczy** [comment]
你的版本太老了。。更新吧。。
