### ISSUE TITLE
Firefox 无法使用自定义保存文件名创建目录

### ISSUE THREAD

**Issue by tanmoumou252** [xifangczy/cat-catch#540]
### 扩展版本号 extension version

2.5.6

### 浏览器

Firefox

### 浏览器版本号

132

### 请详细描述问题

在设置自定义标签后,不论是`/`还是`\`,均无法创建目录 取而代之的是`&bsol;` `&sol;`转义字符
```
${title|slice:0,8}/[${title|slice:0,8}]${title|slice:9,25}${fullFileName}
```

以及 ***有时***在插件面板点击下载按钮会无反应,直接点击抓取到的url即可下载,但直接点url下载会无法使用上述提到的创建目录功能.

所以目前的情况是:
+ 有时候无法点击按钮下载,必须点url下载
+ 如果可以点击按钮下载,也会无法创建目录,路径分隔符被转义了

**Comment by tanmoumou252** [comment]
开aria2后目录可以正常生成了,下载按钮没反应还需要更多的使用

**Comment by xifangczy** [comment]
`有时候无法点击按钮下载,必须点url下载`
遇到点击下载无反应 请使用f12 查看控制台 错误输出。

**Comment by tanmoumou252** [comment]
> > 有时候无法点击按钮下载,必须点url下载
> 
> 遇到点击下载无反应 请使用f12 查看控制台 错误输出。
> 
> 额。。好像firefox的 扩展弹出页面 没有devtools😶 那就尽量把播放地址告诉我 我去复现看看
> 
> 问题已经修复 你可以从github拉去最新代码 下个版本 大概不会那么快时间发布。

 好的,谢谢大佬
 
 好像下载没反应好像是`自定义保存文件名`的问题,使用`slice`之后,最后一个字符如果是`空格`以及title没那么长的话slice不到内容,就可能出现没反应
 
 这是我在用aria2下载显示下载目录生成失败的时候发现的,可能是这个原因,也可能是其他的
