### ISSUE TITLE
这种格式无法下载

### ISSUE THREAD

**Issue by yunskyline** [xifangczy/cat-catch#55]
**bug描述**
![image](https://user-images.githubusercontent.com/47986399/178581146-b67e6ce9-3b38-4979-929f-15e0817e72f5.png)
无法播放，
**浏览器**google
- 名称
- 版本号

**扩展**
 - 版本号猫抓 v2.1.2

**安装方式**
- 官方扩展店
- 源码安装

**涉及网址**（需要注册的，随便找个日本的电话号码就能注好像）
https://webacademy.peek-a-boo.co.jp/film/?id=58

**Comment by xifangczy** [comment]
目前还没有处理dash流的能力，如果你会使用ffmpeg的话 在猫抓设置里添加 mpd后缀 刷新页面 猫抓会得到一个mpd文件。
复制mpd地址
使用ffmpeg下载合并
`ffmpeg -i "https://xxxx.com/xxx.mpd" -c copy down.mp4`

以后可能会支持合并dash流的视频...

**Comment by yunskyline** [comment]
> 还没有处理流的能力，你会使用ffmpeg猫抓设置里的mpd，然后找到发现 地址在猫抓会，如果现在发现一个mpd文件。 `ffmpeg -i "https://xxxx.com/xxx.mpd" -c copy down.mp4`
> 
> 以后可能会支持合并破折号的视频...

说得很详细，但是卡在不会用ffmpeg。

**Comment by yunskyline** [comment]
学会了，安装好 ffmpeg，然后用命令行来下载就行，话说好像不支持断点续传？

**Comment by yunskyline** [comment]
文件太大下载到一半就断了

**Comment by xifangczy** [comment]
https://github.com/xifangczy/cat-catch/issues/55
