### ISSUE TITLE
不知为何，总是会消耗较多cpu资源？

### ISSUE THREAD

**Issue by rmm233** [xifangczy/cat-catch#56]
如图
![QQ截图20220716195230](https://user-images.githubusercontent.com/70251718/179353770-0ac287fd-664c-423c-af71-26b0afb756e0.png)
![QQ截图20220716192251](https://user-images.githubusercontent.com/70251718/179353779-63aea52a-f772-400c-b512-5a59c7b08cb1.png)
![QQ截图20220716195424](https://user-images.githubusercontent.com/70251718/179353850-fc3ca270-0fae-4170-bc70-f4c49aa47a58.png)
不论是有没有点开猫抓，都会这样消耗cpu，但也不是一直会，大概是（一天几次的频率？）

**Comment by xifangczy** [comment]
不建议使用2.1.1 可能会有死循环的BUG 更新吧。
另外，能否找到复现方法？

**Comment by rmm233** [comment]
更新了好像就没有这个问题了。

大概是b站看视频之后出现的问题，随机出现，不知道怎么复现，没有用任何功能，下载都没有，配置没有改动过，默认的。
