### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Shiroha1768** [xifangczy/cat-catch#560]
** 详细描述想要添 加/修改/增强 的功能 **
增加m3u8视频切片下载完用mkv封装

**Comment by xifangczy** [comment]
这个只能交给ffmpeg了 下个版本 m3u8解析器 内自定义名称 不再抹掉后缀。允许自定义后缀 传递给ffmpeg

**Comment by Shiroha1768** [comment]
> 这个只能交给ffmpeg了 下个版本 m3u8解析器 内自定义名称 不再抹掉后缀。允许自定义后缀 传递给ffmpeg

![image](https://github.com/user-attachments/assets/1e06b22a-e726-47dc-8d7a-85fa6b511541)
2.5.7版本，没有看到，怎么设置

**Comment by xifangczy** [comment]
<img width="479" alt="微信图片_20241226154340" src="https://github.com/user-attachments/assets/94306db6-9f77-4930-95f9-4ef4153848bc" />
