### ISSUE TITLE
自定义保存文件名不起作用？

### ISSUE THREAD

**Issue by zzl1223** [xifangczy/cat-catch#569]
### 扩展版本号 extension version

v2.5.6

### 浏览器

Google Chrome

### 浏览器版本号

131.0.6778.109

### 请详细描述问题

当我尝试修改保存的文件名时，发现没有起到作用，尝试过重启，重置配置，卸载重装也没有解决，可以帮我看看吗？感谢您的帮助
我已经进行了相关的设置：
![企业微信截图_17334509616653](https://github.com/user-attachments/assets/db259913-c2dd-4794-8c52-f034acec1364)
![image](https://github.com/user-attachments/assets/77837c85-077a-497c-8fb0-3e44b8e95240)
保存的文件：
![image](https://github.com/user-attachments/assets/978b1ef4-d2be-4f7d-83ab-61f2d859e702)

**Comment by zzl1223** [comment]
我发现手动下载时自定义文件名可以起到作用，但如果选择自动下载则一致是下载到title目录下

**Comment by xifangczy** [comment]
是的 自动下载目前不支持自定义文件名
未来会想办法加上

**Comment by zzl1223** [comment]
> 是的自动下载目前不支持自定义文件名 未来会加上

感谢您的回复，我在使用过程有时候会一直卡在如下界面，请问有好的建议吗？
![Uploading image.png…]()

**Comment by zzl1223** [comment]
请问有没有方法可以让我直接保存文件资源的url？

**Comment by xifangczy** [comment]
> 感谢您的回复，我在使用过程有时候会一直停顿卡在在如下界面（数据载入中），请问有好的建议吗？ ![企业微信截图_17334617061668](https://private-user-images.githubusercontent.com/149457810/393106106-3519f92b-033b-4d21-a37b-0412d8c184f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjMyNzgsIm5iZiI6MTczMzQ2Mjk3OCwicGF0aCI6Ii8xNDk0NTc4MTAvMzkzMTA2MTA2LTM1MTlmOTJiLTAzM2ItNGQyMS1hMzdiLTA0MTJkOGMxODRmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwNTI5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjBmNmNlNjNhOTQzNjYwOThhOWE3OTE0Mzk2YzQ2M2Y3OWZkNWY4NDg1M2RlYmNmNjUyNzc1NjA4MTdjNDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kV0Fccy4OpFVNoAikDa2ZPinkcVeJtgld-tU_GHN3Mg)


按下f12 查看控制台 看看有没有错误输出 把错误输出发给我

**Comment by xifangczy** [comment]
> 请问有没有方法可以让我直接保存文件资源的url？

不是有复制按钮么

**Comment by xifangczy** [comment]
😥 抱歉 chrome 不能用f12打开扩展页面的控制台。。
只能 在弹出页面 右键 检查 打开。。

**Comment by zzl1223** [comment]
> 😥 抱歉 chrome 不能用f12打开扩展页面的控制台。。 只能 在弹出页面 右键 检查 打开。。

感谢回复，我修改一下正则表达式已经可以解决问题了

**Comment by xifangczy** [comment]
感谢提供信息 已经定位到bug位置
正则表达式错误 导致扩展页面无法打开 代价太大了，必须处理这个问题。
