### ISSUE TITLE
解析视频 第一个不显示 有图

### ISSUE THREAD

**Issue by 644517236** [xifangczy/cat-catch#57]
**bug描述**
1.谷歌浏览器+EDGE  猫抓 解析视频 第一个不显示
解析视频 第一个不显示，最近几个版本都是（包括最新v2.2.0）
![2022-07-18_13-47-25](https://user-images.githubusercontent.com/34391099/179452303-86a66481-1464-4206-9051-1f840f210314.png)

**浏览器**
Microsoft Edge
版本 103.0.1264.62 (正式版本) (64 位)

Chrome
版本 103.0.5060.114（正式版本） （64 位）

**扩展**
v2.2.0

**安装方式**
- 官方扩展店
- 源码安装（两种都存在此 BUG）

**涉及网址**
微博...

**Comment by xifangczy** [comment]
你电脑用的什么分辨率

**Comment by 644517236** [comment]
> 是的电脑分辨率是多少.. 额 你的字体明显大了很多 导致按钮变高挡住了一条资源。

17.3寸 4k分辨率的。但是其他插件啥的 不存在这个问题

**Comment by xifangczy** [comment]
之前也有人提出来 我换了很多显示器 浏览器 系统 都没复现 🤣 好吧 下个版本解决... 感谢提交

**Comment by xifangczy** [comment]
多少也是个bug 下个版本会处理
