### ISSUE TITLE
同页面同视频，chrome和Firefox缓存捕捉时均出现奇怪问题

### ISSUE THREAD

**Issue by Mr-114** [xifangczy/cat-catch#575]
### 扩展版本号 extension version

v2.5.6

### 浏览器

Firefox

### 浏览器版本号

v133.0 (64 位)

### 涉及网址

xiaoeknow.com

### 请详细描述问题

在chrome中，使用缓存捕捉功能。当捕捉到中间的时候，视频可以播放，但不完整。当捕捉到结尾时，获取到的视频是损坏的，黑屏，音频混淆。在Firefox中，使用缓存捕捉功能，无缓存捕捉功能的悬浮窗弹出来，原因未知。

**Comment by Mr-114** [comment]
页面需要登陆账号才能访问，故未填写具体网址。
我将持续等待回复，后续可通过其他方式提供登录

**Comment by Mr-114** [comment]
> 某鹅通有其他下载方式 具体查看文档内的 常见问题

好的，我尝试一下

**Comment by Mr-114** [comment]
> 某鹅通有其他下载方式 具体查看文档内的 常见问题

但是在Firefox国际版本上，不显示缓存捕捉的悬浮窗，是程序bug吗？应该不是被拦截了吧应该

**Comment by xifangczy** [comment]
Firefox 暂不支持所有脚本功能 上一个版本更新错误 导致脚本功能按钮被显示出来了 是个bug
下一个猫抓版本 才让Firefox支持脚本功能。

**Comment by Mr-114** [comment]
> Firefox 暂不支持所有脚本功能 上一个版本更新错误 导致脚本功能按钮被显示出来了 是个bug 下一个猫抓版本 才让Firefox支持脚本功能。

好的，谢谢！
