### ISSUE TITLE
应该是腾讯课堂更改密钥算法问题。目前已经不能爬取。

### ISSUE THREAD

**Issue by w0028long** [xifangczy/cat-catch#58]
LOG 2022-07-24
Save Path: D:\软件\m3u8cli\N_m3u8DL-CLI_v3.0.2_with_ffmpeg_and_SimpleG\Logs
Task Start: 2022-07-24 12:46:32
Task CommandLine: "D:\软件\m3u8cli\N_m3u8DL-CLI_v3.0.2_with_ffmpeg_and_SimpleG\N_m3u8DL-CLI_v3.0.2.exe" 

12:46:32.329 / (NORMAL) 开始解析 https://1258712167.vod2.myqcloud.com/fb8e6c92vodtranscq1258712167/9f8944e8387702303410630857/drm/voddrm.token.dWluPTM2MjExMTMxNDtza2V5PTtwc2tleT07cGxza2V5PTAwMDQwMDAwNDc4NTBmOWU0MWNhNjVlNGE1OTQ1NmNkNGYwMzcyMTRiNzdkNDkzNDEyY2EwNGJjYzg0MGEyZDkwNTEyMzVmNjI5YTk3MWRjZDMyYzdhNzg7ZXh0PTt1aWRfdHlwZT0wO3VpZF9vcmlnaW5fdWlkX3R5cGU9MDt1aWRfb3JpZ2luX2F1dGhfdHlwZT0wO2NpZD0zNDAzOTc7dGVybV9pZD05MTM1NzI0Njg7dm9kX3R5cGU9MDtwbGF0Zm9ybT0z.v.f56150.m3u8?t=62E75786&exper=0&us=6750441523565531111&sign=7a6a0e92db2762a6cbf7eaf6b04dbc8b
12:46:33.265 / (NORMAL) 获取m3u8 key... https://ke.qq.com/cgi-bin/qcloud/get_dk?edk=CiC3bgjUC5CQGX7v4YCtnob%2FZ3NkX%2F6O8hsf6EK8%2B5Zq1RCO08TAChiaoOvUBCokOTMyNDg4YmItOWZjYS00MzFiLWJiYjItNjFmMDhjYjNlYmM3&fileId=387702303410630857&keySource=VodBuildInKMS&token=dWluPTM2MjExMTMxNDtza2V5PTtwc2tleT07cGxza2V5PTAwMDQwMDAwNDc4NTBmOWU0MWNhNjVlNGE1OTQ1NmNkNGYwMzcyMTRiNzdkNDkzNDEyY2EwNGJjYzg0MGEyZDkwNTEyMzVmNjI5YTk3MWRjZDMyYzdhNzg7ZXh0PTt1aWRfdHlwZT0wO3VpZF9vcmlnaW5fdWlkX3R5cGU9MDt1aWRfb3JpZ2luX2F1dGhfdHlwZT0wO2NpZD0zNDAzOTc7dGVybV9pZD05MTM1NzI0Njg7dm9kX3R5cGU9MDtwbGF0Zm9ybT0z
12:46:33.734 / (NORMAL) 写出meta.json
12:46:34.361 / (NORMAL) 开始下载文件
12:46:34.719 / (ERROR) 指定的密钥大小对于此算法无效。

**Comment by xifangczy** [comment]
阿这...请去[https://github.com/nilaoda/N_m3u8DL-CLI/issues](https://github.com/nilaoda/N_m3u8DL-CLI/issues)提交啊😅
