### ISSUE TITLE
Bug error network with famous popular dood.ws platform 

### ISSUE THREAD

**Issue by trimechee** [xifangczy/cat-catch#582]
### 扩展版本号 extension version

2.5.6

### 浏览器

其他基于 Chromium 的浏览器

### 浏览器版本号

132

### 涉及网址

https://dood.ws/e/vtgxbe928lco

### 请详细描述问题

Hi, I have message "error network" when i try to download this video from  famous popular dood.ws platform : 

https://dood.ws/e/vtgxbe928lco

this platform is capital and often used by my favourite streaming site, we hope it will be fixed please, i try with "Live-stream-donwloader" extension that succeeded to detect and donwload this video.

**Comment by xifangczy** [comment]
点击 ![cat-down](https://github.com/user-attachments/assets/34367c09-32fd-41c1-9f14-81d50b0c3866) 使用下载器下载

click ![cat-down](https://github.com/user-attachments/assets/34367c09-32fd-41c1-9f14-81d50b0c3866) to use the downloader to download

**Comment by trimechee** [comment]
Awesome ! Thanks :)
