### ISSUE TITLE
现在猫抓抓取腾讯课堂也是有这个情况啊，虽然能下载，但是不能播放。

### ISSUE THREAD

**Issue by w0028long** [xifangczy/cat-catch#59]
猫抓抓取腾讯课堂的视频现在是无法预览。虽然能下载下来ts结尾的视频。但是改格式也好，用视频转换工具转换也好，最后都是无法播放的状态。这个应该也是腾讯改算法引起的吧？

**Comment by w0028long** [comment]
可以通过捕获来绕过，是我low了。不好意思。

**Comment by xifangczy** [comment]
捕获的声音编码会有问题，需要第三方工具转码，暂无其他解决方案。
腾讯课堂的key不在m3u8文件内，所以解析器没办法解开。
