### ISSUE TITLE
转码为 mp4 后视频时间不一致

### ISSUE THREAD

**Issue by Quackgrass** [xifangczy/cat-catch#61]
**bug描述**
同一个视频，转码为 mp4 后视频时间不一致，mp4 是 ts 格式的几倍，但实际播放时超过的部分无数据。

![image_268](https://user-images.githubusercontent.com/42032091/182014668-b583f63e-299b-4dcc-bd99-671237e0e493.png)

**浏览器**
- 名称 edge
- 版本号 103.0.1264.77 (正式版本) (64 位)

**扩展**
 - 版本号 v2.2.2

**安装方式**
- 官方扩展店
- 源码安装 √

**Comment by xifangczy** [comment]
mp4转码依赖 [mux.js](https://github.com/videojs/mux.js)
确实有这样的BUG，mux.js为在线播放器服务没有考虑会下载到本地，一直没有对这BUG修复。
所以我没有让mp4转码默认勾选上，目前还在测试阶段。接下来会想办法去修复mux.js的问题 或者 寻找别的转码方式。

**Comment by Quackgrass** [comment]
``` cmd
echo off
cls
for %%a in ("*.ts") do ffmpeg -i "%%a" -f mp4 -codec copy "%%~na.mp4
pause
```

这个是我找的用 ffmpeg 批量转的脚本。[来源](https://www.qinyuanyang.com/post/262.html) 

这个能解决问题。你添加个说明就好，处理这个的优先级可以排在后面。

**Comment by xifangczy** [comment]
下个版本2.2.3已经解决了这个问题

你都使用ffmpeg了 不如直接用m3u8DL工具一步到位

**Comment by Quackgrass** [comment]
好的，谢谢。

有尝试 N_m3u8DL-CLI，但直接调用下载不了，手动给参数试了也没成功。猫抓够用了，就没有继续研究了。
