### ISSUE TITLE
直播流调用potplayer预览无法播放

### ISSUE THREAD

**Issue by Swor-dart** [xifangczy/cat-catch#63]
直播流调用potplayer预览无法播放
解析得到m3u8文件也无法播放
这是什么原因呢？

**Comment by xifangczy** [comment]
确定不是potplayer的问题？

**Comment by Swor-dart** [comment]
> 确定不是potplayer的问题？

需要设置什么吗？预览失败，得到的B站的m3u8文件也无法播放，以前一直用的脚本是获取直播流地址的flv流。

**Comment by xifangczy** [comment]
B站直播 有的是flv 有的是m3u8 你可以尝试用 模拟手机 然后获得到flv 这个可以正常用potplayer预览。
这个issues我关了 我不认为这是扩展的BUG 扩展已经忠实的列出了播放源。

**Comment by Swor-dart** [comment]
> B站直播 有的是flv 有的是m3u8 你可以尝试用 模拟手机 然后获得到flv 这个可以正常用potplayer预览。 这个issues我关了 我不认为这是扩展的BUG 扩展已经忠实的列出了播放源。

我提这个issure没说是bug啊，就是纳闷为啥预览能行但是没法导入到potplayer里播放，刚试了模拟手机LOL的flv直播流，还是无法播放。。。
