### ISSUE TITLE
无法抓取

### ISSUE THREAD

**Issue by nam918** [xifangczy/cat-catch#64]
**bug描述**
 
闻不到啊。。

**浏览器**
- 名称 Chrome
- 版本号 104.0.5112.81（正式版本） （64 位）

**扩展**
 - 版本号 v2.2.2
 
**安装方式**

- 源码安装

**涉及网址**
https://www.ohli24.net/c/%EC%98%A4%EB%B2%84%EB%A1%9C%EB%93%9C%20IV

**Comment by xifangczy** [comment]
设置 添加一条正则匹配
`https://ndoodle\.xyz/cdn/hls/.*/master\.txt` 扩展为 `m3u8`

**Comment by nam918** [comment]
谢谢。解决了。
