### ISSUE TITLE
如何调用m3u8dl://协议

### ISSUE THREAD

**Issue by Blackmaginitaimei** [xifangczy/cat-catch#67]
开启了调用功能，参数也设置了。然后在popup页面点m3u8资源的下载图标，没有任何反应。不知道哪里的问题

**Comment by xifangczy** [comment]
恢复 默认参数 能不能调用。

**Comment by xifangczy** [comment]
点击 重置其他设置 恢复默认参数 看是否能正常调用

**Comment by Blackmaginitaimei** [comment]
> 先确定m3u8dl协议是不是注册完成了。 在浏览器地址栏手动输入 回车，能不能打开m3u8DL`m3u8dl://`

懂了， 谢谢大佬，搞定。十分感谢
