### ISSUE TITLE
[Support] N_m3u8DL-RE

### ISSUE THREAD

**Issue by Mr-xn** [xifangczy/cat-catch#68]
原m3u8dl 作者新的项目[N_m3u8DL-RE](https://github.com/nilaoda/N_m3u8DL-RE)，支持跨平台的，目前还是 dev .
试用了下还是不错的，希望猫爪在有空的时候可以加上对其的支持！
感谢开发这么好用的chrome 插件！

**Comment by Mr-xn** [comment]
类似这样的格式就可以直接使用:
```
"https://m3u8.xxx.com/xxx/xxx/xxxxx.m3u8" --save-dir "/path/to/download/" --save-name "filename" --thread-count "32" --append-url-params -H "Referer:https://xxx.xxx/"
```

**Comment by xifangczy** [comment]
我也在关注新版本，目前还在开发早期而且还没有调用协议，等新版有调用协议会第一时间加上。
可以改写 复制选项 设置 把m3u8和mpd写成
`"$url$" --save-dir "/path/to/download/" --save-name "$title$" --thread-count "32" --append-url-params -H "Referer:$referer$"`
之后对m3u8和mpd文件点击复制图标，手动打开N_m3u8DL-RE 直接粘贴运行。

**Comment by magicdawn** [comment]
有个小问题, 模板里没有, 复制出来的会带着, v2.3.2

```
--maxThreads "32" --downloadRange "0-XXX"
```

`--maxThreads` / `--downloadRange` 无法识别

**Comment by xifangczy** [comment]
> `--maxThreads` / `--downloadRange` 无法识别

在 m3u8解析器 里复制的，因为解析器界面有 范围和线程数的设置项 会覆盖掉你设置的模板参数。
