### ISSUE TITLE
想问一下要如何直接调用N_m3u8下载器下载呢？没有找到填写调用本地程序目录的地方

### ISSUE THREAD

**Issue by artemisluck97** [xifangczy/cat-catch#69]
猫抓已经支持了 [N_m3u8DL-CLI]m3u8dl:// 只需要在设置里面开启 调用m3u8dl://协议下载m3u8 选项，之后直接在popup页面点击m3u8下载即可。
对于这里我没太懂，直接点击m3u8下载的是m3u8文件，并没有调用N_m3u8下载器，所以本地的N_m3u8要如何调用呢？请作者指点~感谢

**Comment by xifangczy** [comment]
[https://o2bmm.gitbook.io/cat-catch/docs/m3u8dl](https://o2bmm.gitbook.io/cat-catch/docs/m3u8dl)
