### ISSUE TITLE
你好，有个很重要点问题， 请看这里

### ISSUE THREAD

**Issue by vipei** [xifangczy/cat-catch#7]
猫爪抓取了100多个.TS视频 。 下拉框超出屏幕限制。 无法点击到下载 怎么破.

**Comment by xifangczy** [comment]
没有m3u8文件吗？非要等ts完么。。

**Comment by AlemAblat** [comment]
> 没有m3u8文件吗？非要等ts完么。。

提示Key错误。加密的怎么下载？也就是现在的网易云课堂的有了m3u8文件可是下载也是提示key错误

**Comment by Huaweidev** [comment]
> 没有m3u8文件吗？非要等ts完么。。

网页直播视频的m3u8文件没有完整视频，无法直接通过m3u8文件下载。只能一边播放一边用猫爪嗅探地址。但是视频有四五个小时，等都嗅探好再点击猫爪的下载全部，结果提示“无法下载，没有文件”，应该是时间戳或者密钥过期了。
