### ISSUE TITLE
关于下载onedrive的非原画时，音频内容下载合并后内容不一致

### ISSUE THREAD

**Issue by aawwsslll** [xifangczy/cat-catch#70]
**bug描述**
解析不同分辨率，视频是可以下载的，但是和音频分开的。
单独下载音频，下载合并以后出现了问题，对比在线播放的音频内容出现异常。
**浏览器**
火狐
- 名称
- 版本号
104
**扩展**
 - 版本号
2.2.4

**安装方式**
- 官方扩展店
- 源码安装

**涉及网址**
https://tcconveniencestores-my.sharepoint.com/:v:/g/personal/asmr04_tcconveniencestores_onmicrosoft_com/EanSUwtcKdBPgtonC8wtms0BU9XRik1SAb_a3_E5QEf19w?e=YlsCCQ

上面是我测试的视频，你解析后可以试试下载非原画质，然后音频就是视频分开的，然后下载完成出现了
音频和视频原音频不一致的问题（可能是丢失或者顺序错乱导致的），实际上这个软件很强大了，我试过用其他的软件
根本无法下载onedrive的其他分辨率视频（只能下载原画）

另外提一个建议，就是在下载解析m3u8内容时，有时候有些片段会出错，需要一个一个点重试才能下完，有时候分段比较多需要点几十个，希望可以加一个按钮，点一下就就是把需要重试的片段加入到队列排队，不需要手动一个个去点重试就好了，不知道这种功能能否实现。

**Comment by xifangczy** [comment]
感谢提交... 
是mpd解析器的BUG，这视频有两个音频只找到一个，另一个OriginalAudio才是你需要的。

现在解析器还很简陋，使用的还是第三方解析工具，要解决这个问题只能开坑写一个mpd解析器，工程量比较多，慢慢来吧。

> 另外提一个建议，就是在下载解析m3u8内容时，有时候有些片段会出错，需要一个一个点重试才能下完，有时候分段比较多需要点几十个，希望可以加一个按钮，点一下就就是把需要重试的片段加入到队列排队，不需要手动一个个去点重试就好了，不知道这种功能能否实现。

👌

**Comment by xifangczy** [comment]
fixed
