### ISSUE TITLE
火狐  菜单选项显示不完整

### ISSUE THREAD

**Issue by ghost** [xifangczy/cat-catch#75]
**bug描述**
下图是未隐藏到火狐折叠菜单（即图标位于工具栏）时的显示，部分下拉选项不可见。
![图片](https://user-images.githubusercontent.com/111456578/193341531-66ad3a5f-611a-4518-97d0-6827624b622f.png)

下图是隐藏到折叠菜单时的显示，显示有问题+部分不可见。
![图片](https://user-images.githubusercontent.com/111456578/193341976-99521765-42a3-4558-be2f-ca5762c46a17.png)

**扩展**
 - 版本号
v2.2.5
**安装方式**
- 官方扩展店

**Comment by xifangczy** [comment]
扩展使用的 Chrome Manifest V3 里的 scripting.executeScript 方法注入脚本，firefox对该方法支持不完整
[executeScript Browser compatibility](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/executeScript#browser_compatibility)
对 `world` 的支持 仍不完善。 所以 firefox暂时没脚本注入功能，隐藏了，这是正常的。
本以为之后firefox会慢慢兼容过去，结果105还没...看来不打算完整实现executeScript  API了 以后也许会为firefox单独设计一个。

折叠菜单显示不正确，我认为这是firefox的BUG 几乎所有插件折叠菜单时候都显示不完整。
