### ISSUE TITLE
关于TS文件下载后合并为MP4的BUG

### ISSUE THREAD

**Issue by senghor-song** [xifangczy/cat-catch#76]
**bug描述**
原视频文件是TS格式，不适用MP4合并文件，则是正常视频文件
如果使用MP4合并文件，则文件最后会有一段真空显示，但是不影响播放，我使用其他软件转换TS为MP4文件则不会出现该问题

异常显示视频进度条
![image](https://user-images.githubusercontent.com/29698430/193500202-e44444d0-1b50-446b-b4f3-a1268b156cbd.png)

正常视频进度条
![image](https://user-images.githubusercontent.com/29698430/193500320-5bfa8c7d-7beb-4c85-abf2-c468dbc84fe6.png)

**扩展**
 - 版本号
v2.2.5
Edge浏览器

**安装方式**
- 官方扩展店

**涉及网址**
https://sexbjcam.com/2022/10/03/kbj22100336_turyyy_20220815/

**Comment by xifangczy** [comment]
2.3.0 ffmpeg在线转码解决
