### ISSUE TITLE
某个视频 edge浏览器可以，chrome浏览器不行

### ISSUE THREAD

**Issue by linhua55** [xifangczy/cat-catch#79]
**bug描述**
这个视频 使用edge浏览器中的 猫抓，可以嗅探到视频（会显示分辨率多少） 并下载 播放，但是在chrome浏览器中，猫抓虽然也能嗅探到，但是会显示“无视频”，实际下载下来播放也是没有视频的
**扩展**
 - 版本号
chrome 版本 106.0.5249.91（正式版本） （64 位）
edge 版本 106.0.1370.34 (正式版本) (64 位)
**安装方式**
- 官方扩展店

**涉及网址**
https://mp.weixin.qq.com/s/Rjqf9Lz5NFPOxDGnjwy4yg

**Comment by xifangczy** [comment]
哎... 企鹅又魔改了啥...
chrome和edge给的m3u8地址都不一样。。chrome获取到的 ts文件有点问题？导致解析器和转码器都不能正常识别。
临时解决 不使用 `mp4转码` 直接合并成ts 本地播放器能正常播放或使用 ffmpeg 转码。

**Comment by xifangczy** [comment]
企鹅和某些网站开始启用H.265编码的视频
目前hls解析器和转码器都不支持，取消mp4转码，合并后再使用本地工具转码。
等待以后支持H.265

**Comment by xifangczy** [comment]
> 因为·Chrome 105开始支持HEVC系统解码了，Chrome 106默认开启了。

HEVC没问题。但按照m3u8规范 HEVC应该使用 fmp4 而不是ts格式。这种“怪异”的格式，在线解码工具目前都无法处理。
