### ISSUE TITLE
可否上架到Edge的应用商店

### ISSUE THREAD

**Issue by ljcbaby** [xifangczy/cat-catch#8]
可否上架到Edge的应用商店

**Comment by dylanleesky** [comment]
还有360市场，或者提供个签名打包好的吧。


@ljcbaby   估计Edge也会被下掉的，Edge和Chrome一样都属于国外区域，对版权保护很严格。

**Comment by ljcbaby** [comment]
盗版的都出来了

**Comment by dylanleesky** [comment]
> 盗版的都出来了
> https://microsoftedge.microsoft.com/addons/detail/%E8%A7%86%E9%A2%91%E4%B8%8B%E8%BD%BD%E7%A5%9E%E5%99%A8/hcidhlkhopdfikpbcldamannphlpkpkd?hl=zh-CN


这个应该是正版的吧。。。。
https://microsoftedge.microsoft.com/addons/detail/%E7%8C%AB%E6%8A%93/dbopnkgegdeahajfhboecpphnnoeaech

**Comment by CloudyEagle** [comment]
还是希望能在其他的插件市场做备份吧，也希望原作者@xifangczy 亲自放一个上去，或者这个链接就是原作者的——
https://microsoftedge.microsoft.com/addons/detail/猫抓/dbopnkgegdeahajfhboecpphnnoeaech

**Comment by ljcbaby** [comment]
> 还有360市场，或者提供个签名打包好的吧。
> 
> @ljcbaby 估计Edge也会被下掉的，Edge和Chrome一样都属于国外区域，对版权保护很严格。

360的我看了一下，有的

**Comment by StrollStars** [comment]
感觉很奇怪，[CoCoCut](https://chrome.google.com/webstore/detail/video-downloader-cococut/gddbgllpilhpnjpkdbopahnpealaklle)可以存在。
