### ISSUE TITLE
关于最大请求时长的修改设置

### ISSUE THREAD

**Issue by senghor-song** [xifangczy/cat-catch#81]
**bug描述**
我发现在某些网址进行抓取时，由于种种原因，网速不理想，但是猫抓限制30秒最大请求时长，会导致单次请求超过30秒，我测试过多次请求，大约需要40-50秒甚至更长时间才能下载完毕，但是这期间仍然可以请求资源（下载速度较慢）

**请问能否开放修改最大请求时长的设置？**

理由有两个：
1. 抓取网址可能并未设置请求最大时长或者设置的最大时长超过30秒
2. 目前的30秒限制单个文件的50%-70%已下载，但是由于时长限制下载失败，需要重新下载（超时失败概率很高），这就直接导致某个文件需要手动反复点击下载

以下为截图示例，部分请求超过30秒被终止
![image](https://user-images.githubusercontent.com/29698430/194712571-17072771-1093-43e3-87d3-fcd674cb5c12.png)

Postman测试其中某个请求，用时58秒
![image](https://user-images.githubusercontent.com/29698430/194712903-3924e593-bd21-457f-ac8f-f0f3b0e03d5c.png)

**扩展**
 - 版本号 v2.2.5

**安装方式**
- 官方扩展店

**涉及网址**
由于情况较多无法稳定复现

**Comment by xifangczy** [comment]
是的，每个切片下载为避免不可控，主动设置的30秒超时。
行吧...确实需要调整下
下个版本，正常下载仍然30秒超时，但重试下载不再限制超时。
