### ISSUE TITLE
建议自动保存上次修改的下载线程数

### ISSUE THREAD

**Issue by super302** [xifangczy/cat-catch#82]
**扩展**
 - v2.2.5

我在“[N_m3u8DL-CLI]参数”中尝试添加“--maxThreads "16"”，但不起作用。
版本是v2.2.5，建议自动保存上次修改的下载线程数。或者可以手动设置默认线程数。
因为有些网站太多线程下载容易出问题，默认的32线程略显奔放，经常需要手动调低。

**Comment by xifangczy** [comment]
解析器里的调用按钮 确实会覆盖线程数设置
开启了N_m3u8DL-CLI 下载 你可以直接在popup 直接点击下载不用进解析器

下个版本改进

**Comment by super302** [comment]
感谢回复。
有些网站的m3u8是分层级的，里面会嵌套多个分辨率和码率的下级m3u8，所以需要点进解析器里进行“合并下载”。而且在解析器里可以看到是否有切片下载失败，还能手动重试。
不过我已经找到修改下载线程数的方法了，就是不知道是否真起作用了还是只是障眼法。
我的做法是修改插件文件夹中“m3u8.html”的源代码，把id="threadDiv"中input标签的value值改成自己自定义的默认值。
不管怎么样，感谢您的分享，您的作品非常优秀！！！
