### ISSUE TITLE
[建议] 增加两个 m3u8DL 的参数

### ISSUE THREAD

**Issue by purple4pur** [xifangczy/cat-catch#83]
配合以下两个命令行参数基本可以全自动重试下载：
```
OPTIONS:

  --retryCount               (Default: 15) 设定程序的重试次数
  --stopSpeed                当速度低于此值时，重试(单位为KB/s)
```

**Comment by xingkb** [comment]
![eac68f50d24d1540152aac5503f58619_spaces%2FzebSpGaUVek4pGh23rNN%2Fuploads%2FhODLfuYF44LrJw7gZ0lh%2F2_alt=media token=3a973cc2-1acb-426a-89b5-03c536eca703](https://user-images.githubusercontent.com/60958222/203834787-17b41165-1997-4a6b-906e-2a601c9acc5c.png)
设置中修改就是了

**Comment by purple4pur** [comment]
了解了，感谢
