### ISSUE TITLE
建议 支持手机版的iceraven浏览器

### ISSUE THREAD

**Issue by lostever** [xifangczy/cat-catch#84]
请问手机版火狐系浏览器有没有使用方法

**Comment by lostever** [comment]
试了下安卓kiwi浏览器可以安装，但无法使用，好像是无法定位到页面，因为要打开扩展总是要单独打开一个页面，而嗅探只能嗅探这个扩展的页面，因此不能对之前的页面进行嗅探，就很难受

**Comment by xifangczy** [comment]
试了没问题 可以用。也有不少人是在kiwi浏览器上用。

**Comment by lostever** [comment]
大佬牛逼
