### ISSUE TITLE
可不可以增加potplayer打开

### ISSUE THREAD

**Issue by Fullzzz** [xifangczy/cat-catch#9]
有些网页播放器太垃圾了，有了m3U8地址再复制打开太麻烦了能不能增加个调用potplayer播放

**Comment by xifangczy** [comment]
扩展目前还做不到本地应用调用...如果一个扩展可以随便打开本地应用... 那太可怕了。

**Comment by Fullzzz** [comment]
油猴有个斗鱼的脚本有个通过potplayer打开的，把当前直播地址放到potplayer，Chrome想这种打开都会有提示框给你确认的不用担心。

**Comment by 986244073** [comment]
我已经实现了 哈哈

**Comment by xifangczy** [comment]
找到了potplayer的调用方式，已经增加该功能

**Comment by xifangczy** [comment]
> 我已经实现了 哈哈

那你不怎么提交代码？
