### ISSUE TITLE
求解 里面地址里视频 怎么抓? 都没扩展名

### ISSUE THREAD

**Issue by longqing32** [xifangczy/cat-catch#91]
https://jx.aidouer.net/?url=https://v.youku.com/v_show/id_XNTkxMzgxMzMwMA==.html?spm=a2hbt.13141534.1_2.5&s=efcf7daa538f412e803d

**Comment by longqing32** [comment]
抓包m3u8?v  都是视频碎片 又不能识别抓包 所以求解

**Comment by xifangczy** [comment]
使用`深度搜索`

**Comment by longqing32** [comment]
我找了一圈没有 深度搜索 按钮

**Comment by longqing32** [comment]
> 使用`深度搜索`

我找了一圈没有 深度搜索 按钮

**Comment by xifangczy** [comment]
firefox浏览器？

**Comment by longqing32** [comment]
> firefox浏览器？

360极速版

**Comment by longqing32** [comment]
要是能增加 不过滤的话 就全部抓包了.自己挑碎片下载合成.

**Comment by xifangczy** [comment]
深度搜索和捕获脚本需要102版本以上chromium内核。360急速版版本不够。


> 要是能增加 不过滤的话 就全部抓包了.自己挑碎片下载合成.
可以的 选中你要合并的ts 点击 `复制所选`
其他功能 - M3U8解析器 粘贴到 `输入m3u8内容 或 ts碎片列表` 内 点击解析即可
