### ISSUE TITLE
B站视频没有声音

### ISSUE THREAD

**Issue by StrollStars** [xifangczy/cat-catch#96]
**bug描述**
下载的视频只有画面没有声音

**扩展**
 - 2.2.8

**浏览器**
 - Chrome 104

**涉及网址**
https://www.bilibili.com/bangumi/play/ep684691

**Comment by xifangczy** [comment]
B站音频和视频分开的 你会看到两个资源。

**Comment by miaozilong** [comment]
把下载的两个MP4合并就好了

**Comment by StrollStars** [comment]
@xifangczy @miaozilong 确实可以，不过再请教下，为什么这个链接的音频文件会这么大？差不多纯视频的一半体积。

**Comment by miaozilong** [comment]
> @xifangczy @miaozilong 确实可以，不过再请教下，为什么这个链接的音频文件会这么大？差不多纯视频的一半体积。

不知道 我的硬盘够  不管他 哈哈😃
